### ISSUE TITLE
[help wanted]: website ui improvement

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#10089]
### Anything you want to discuss about vllm.

<img width="236" alt="image" src="https://github.com/user-attachments/assets/c8a23dda-5fe5-4829-b369-a65917e29bec">

currently, "ask AI" and doc version selection are overlapped.

we should move doc version selection to the left.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by rafvasq** [comment]
From what I've read, moving the version selector isn't supported out of the box with the current [book theme](https://sphinx-book-theme.readthedocs.io/en/stable/) which extends from the PyData theme (https://github.com/pydata/pydata-sphinx-theme/issues/705) and otherwise I think it would be a busy CSS workaround unless vLLM adopts the [ReadTheDocs theme to easily attach it to the sidebar](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-flyout_display)

I think the simplest solution would be to move the AskAI button instead and then, using the current theme, I could also work on introducing the theme's supported [Version Selector](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html). Let me know what you think @youkaichao!

**Comment by youkaichao** [comment]
didn't expect it is complicated as this. thanks for your hard work, and let's keep the AskAI button in the left then.
