### ISSUE TITLE
[Misc]: Potential division by zero in csrc/cpu/attention.cpp

### ISSUE THREAD

**Issue by Xaenalt** [vllm-project/vllm#11068]
### Anything you want to discuss about vllm.

Our scanners picked this one up, just as a potential issue:

https://github.com/vllm-project/vllm/blob/9b9cef3145381721fa950c89718fe71849ac2a55/csrc/cpu/attention.cpp#L97
and
https://github.com/vllm-project/vllm/blob/9b9cef3145381721fa950c89718fe71849ac2a55/csrc/cpu/attention.cpp#L129

both have the potential to divide by zero, though this would only ever happen if sum happens to be zero, which would only ever seem to be possible in an extreme edge case.

I can draft up a PR if it seems worth fixing.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
I think the division by zero can hardly happen because we are using a "reduce" softmax implementation here:

$$\text{Softmax}(z_i) = \frac{e^{x_{i}-M}}{\sum_{j=1}^K e^{x_{i}-M}} \ \ \ for\ i=1,2,\dots,K$$

$$M=\text{Max}(x_i) \ \ \ for\ i=1,2,\dots,K$$

so that the denominator ($\sum_{j=1}^K e^{x_{i}-M}$) is always larger than 1.

**Comment by Xaenalt** [comment]
Yeah, it's very unlikely because the entire sum on the denominator would have to be zero, which I suspect only a specially crafted model would be able to generate, but it was on our scanner so I figured worth asking if it was worth looking at
