### ISSUE TITLE
[Installation]: vllm-flash-attn's pytorch is not compatible with vllm 0.6.5's

### ISSUE THREAD

**Issue by jfcherng** [vllm-project/vllm#11283]
### Your current environment

As the title, `vllm-flash-attn` pins `torch==2.4.0` but `vllm` 0.6.5 requires `torch==2.5.1`.

### How you are installing vllm

```sh
$ uv pip install vllm==0.6.5 vllm-flash-attn
  × No solution found when resolving dependencies:
  ╰─▶ Because vllm==0.6.5 depends on torch{platform_machine != 'aarch64'}==2.5.1 and
      vllm-flash-attn>=2.6.1 depends on torch==2.4.0, we can conclude that vllm==0.6.5 and
      all of:
          vllm-flash-attn==2.6.1
          vllm-flash-attn==2.6.2
       are incompatible. (1)
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by noooop** [comment]
LOL 

Turn serious face:

from https://github.com/vllm-project/vllm/pull/8245

vllm-flash-attn is compiled together with vllm instead of separately. 
So you do not need to install vllm-flash-attn separately.

Obviously, the subsequent cmake files in the vllm-flash-attn warehouse were not updated along with vllm, 
so now there is no way to install vllm-flash-attn separately.

**Comment by jfcherng** [comment]
I guess my issue has been resolved.
