### ISSUE TITLE
vllm implementation

### ISSUE THREAD

**Issue by Shikamaru5** [vllm-project/vllm#1133]
It isn't totally clear to me how we're supposed to be running this. For example, it doesn't seem to work in tandem with transformers, calling the model with LLM I can't also call quantization_config. Also am I just calling LLM or am I supposed to be calling LlamaForCausalLM, AutoTokenizer, etc? If these things are easy fixes great, otherwise I believe there's clearly some work that needs to be done, seeing as it can't be used straight out of the box.

**Comment by viktor-ferenczi** [comment]
It depends on your use case. There are the following two main modes you can use vLLM:

### Start vLLM as a server

Start vLLM as a server with its own API or a (mostly) OpenAI compatible one and connect to it from your solution.

Pros: No model load on startup, quicker. More scalable.

Cons: Higher complexity, very slight latency increase on making requests due to the use of HTTP.

#### vLLM's own API

Start vLLM like this (customize):
```sh
python -O -u -m vllm.entrypoints.api_server \
    --host=127.0.0.1 \
    --port=8000 \
    --model=$HF_MODEL_ID \
    --tokenizer=hf-internal-testing/llama-tokenizer
```

Use `--host=0.0.0.0` if you want to reach the server from your network.

Please see the [documentation](https://vllm.readthedocs.io/en/latest/) or `--help` for more parameters, for example:
```
    --tensor-parallel-size=2
    --block-size=16
    --swap-space=8
```

In your Python code you can use the following REST API client to connect: https://pypi.org/project/vllm-client/

Its source is currently in my personal GitGub, but I hope for this being moved into the vLLM GitHub Organization soon ( @WoosukKwon ) : https://github.com/viktor-ferenczi/vllm-client

I personally found this way the best, because it nicely separates the LLM hosting (vLLM) from my own logic and allows for way faster iteration times in development (no wait time on loading the model).

#### OpenAI API

Start vLLM like this (customize):
```sh
python -O -u -m vllm.entrypoints.openai.api_server \
    --host=127.0.0.1 \
    --port=8000 \
    --model=$HF_MODEL_ID \
    --tokenizer=hf-internal-testing/llama-tokenizer
```

Use `--host=0.0.0.0` if you want to reach the server from your network.

Use OpenAI's openai Python module to connect. Sync and async examples:
[vllm-openai-api-examples.zip](https://github.com/vllm-project/vllm/files/12705594/vllm-openai-api-examples.zip)

### Use vLLM via its Python API

Use vLLM directly via its Python API, see in the [QuickStart - Documentation](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html).

Pros: Direct control over vLLM, starts with your process.

Cons: Potentially slow startup due to having to load the model.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
