### ISSUE TITLE
Can we load a model in 4bit or 8bit?

### ISSUE THREAD

**Issue by MrigankRaman** [vllm-project/vllm#1155]
I have a A10G GPU with 23GB VRAM and I want to run inference on a 13B model which in bf16 is 26GB. Does VLLM support quantized models so that I can run inference?

**Comment by viktor-ferenczi** [comment]
The upcoming 0.2.0 release will support 4-bit AWQ models.:
PR: https://github.com/vllm-project/vllm/issues/1089

You can clone this Git repository, switch to the PR's branch and compile vLLM locally (see in the README). It worked for me perfectly on CUDA 11.8 and a 4090 GPU (24GB VRAM), so it should work on your A10 as well.

[TheBloke released a lot of AWQ models](https://huggingface.co/models?search=TheBloke%20AWQ) this week, therefore you have a wide selection of ready to use models. Download only models which has the `quant_config.json` file, because that's required by vLLM to run AWQ models.

[There is a PR for W8A8 quantization support](https://github.com/vllm-project/vllm/pull/1112), which may give you better quality with 13B models. I haven't tested this branch yet, but you're free to try. Please share your experience on the Discord (invite is in the README).

**Comment by viktor-ferenczi** [comment]
@WoosukKwon Please close this ticket as it has been answered. Thanks.

**Comment by viktor-ferenczi** [comment]
4-bit AWQ (A4W16) quantization has already been implemented in vLLM 0.2.0, please search for model son HF: `TheBloke AWQ`

At the time of writing vLLM 0.2.0 has not been not released yet, so please clone the `main` and build it from source. Instructions are in [CONTRIBUTING.md](CONTRIBUTING.md)

Support for 8-bit AQW (A8W8) is in the making, which is expected to be better than plain 8-bit quantization. Please follow progress on #1112, once it is merged you should be able to use it after a rebuild.

This ticket can be closed.

**Comment by Tatiats7** [comment]
Hi! Is there a way to run tensor parallelism on an int-8 quantized Llama 3.1 70B instruct model?

**Comment by hmellor** [comment]
Yes, with the `--tensor-parallel-size` argument
