### ISSUE TITLE
[Bug]OOM occurs after setting gpu_memory_utilization to 1.0

### ISSUE THREAD

**Issue by wjj19950828** [vllm-project/vllm#1298]
When I execute the following command, it runs llama2 70b

```shell
python3 benchmark_latency.py  --model llama2_70b --input-len 1536 --output-len 512 --batch-size 11 -tp 2
```

The default gpu_memory_utilization is 0.90, and the above command can run normally.

But if I set the gpu_memory_utilization default value to 1.0 and run the same command, OOM occurs
![image](https://github.com/vllm-project/vllm/assets/19977378/18447fec-0358-4d84-bd44-4747fc526bc2)

Is this reasonable? What is the maximum value that gpu_memory_utilization can be set to? Thanks~

**Comment by wjj19950828** [comment]
@viktor-ferenczi @WoosukKwon
Do you have any suggestions over there?

Thanks~

**Comment by WoosukKwon** [comment]
Hi @wjj19950828, thanks for the great question. Theoretically, `gpu_memory_utilization=1.0` should work. However, because we approximately profile the model's memory usage (which is a limitation of using PyTorch), setting `gpu_memory_utilization` too high might cause OOM. That is, vLLM may pre-allocate too large tensors for KV cache. In practice, setting the value from 0.9 (default) to 0.95 is safe and results in good performance.

**Comment by chhaj5236** [comment]
Hi @WoosukKwon, could please elaborate more details about why OOM might occur when setting gpu_memory_utilization too high? I thought `gpu_memory_utilization` should include model weights and KV cache. Why more GPU reserved will cause OOM, is there anything else consuming gpu and not counted in reserved gpu (model weights and KV cache)?

**Comment by cadedaniel** [comment]
there are other things like intermediate activations that can consume additional GPU memory. The amount depends on the exact kernel, so it's hard to predict. That's why it is recommended to use 0.95 or 0.90.
