### ISSUE TITLE
 The detected CUDA version (11.8) mismatches the version that was used to compile       PyTorch (12.1). Please make sure to use the same CUDA versions.

### ISSUE THREAD

**Issue by Ikkyu321** [vllm-project/vllm#1548]
Hi guys, I install vllm failed with pip install -e .
The error messages shows below:

```
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
```

My driver version is 535.113.01 and cuda version is 11.8，python version is 3.8.
![image](https://github.com/vllm-project/vllm/assets/87475073/2096c9a5-b869-4d84-be1f-0b7e61072f9a)

I have no idea about this issue, even though I pre-install pytorch=2.0.1+cu11.8, it still failed.
Will appreciate some help on it.

**Comment by olariuromeo** [comment]
up

**Comment by xin-li-67** [comment]
Hi, what cuda driver is installed on your cuda device?? Perhaps you need to uninstall your current cuda driver and install the archived 11.8 version. Then reinstall this version of the pytorch again.

**Comment by Ikkyu321** [comment]
> Hi, what cuda driver is installed on your cuda device?? Perhaps you need to uninstall your current cuda driver and install the archived 11.8 version. Then reinstall this version of the pytorch again.

![image](https://github.com/vllm-project/vllm/assets/87475073/3c1ec3ba-6b34-4fa3-943d-c13beae2ac27)
![image](https://github.com/vllm-project/vllm/assets/87475073/e672bb56-2a59-4c2e-a5ab-f4b16feebf6f)
I have upgraded my cuda driver to 535.113.01 and reinstall pytorch with 2.0.1+cu118，it still failed.

**Comment by xin-li-67** [comment]
> > Hi, what cuda driver is installed on your cuda device?? Perhaps you need to uninstall your current cuda driver and install the archived 11.8 version. Then reinstall this version of the pytorch again.
> 
> ![image](https://user-images.githubusercontent.com/87475073/280221579-3c1ec3ba-6b34-4fa3-943d-c13beae2ac27.png) ![image](https://user-images.githubusercontent.com/87475073/280221864-e672bb56-2a59-4c2e-a5ab-f4b16feebf6f.png) I have upgraded my cuda driver to 535.113.01 and reinstall pytorch with 2.0.1+cu118，it still failed.

This 535.113.01 is the version number of your nvidia graphics card driver, not the cuda driver. You can use `nvcc -V` to check your current cuda driver version. You have to remove and reinstall the cuda 11.8 from this [link](https://developer.nvidia.com/cuda-11-8-0-download-archive).

**Comment by Ikkyu321** [comment]
> > > Hi, what cuda driver is installed on your cuda device?? Perhaps you need to uninstall your current cuda driver and install the archived 11.8 version. Then reinstall this version of the pytorch again.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/87475073/280221579-3c1ec3ba-6b34-4fa3-943d-c13beae2ac27.png) ![image](https://user-images.githubusercontent.com/87475073/280221864-e672bb56-2a59-4c2e-a5ab-f4b16feebf6f.png) I have upgraded my cuda driver to 535.113.01 and reinstall pytorch with 2.0.1+cu118，it still failed.
> 
> This 535.113.01 is the version number of your nvidia graphics card driver, not the cuda driver. You can use `nvcc -V` to check your current cuda driver version. You have to remove and reinstall the cuda 11.8 from this [link](https://developer.nvidia.com/cuda-11-8-0-download-archive).

![image](https://github.com/vllm-project/vllm/assets/87475073/30540f28-9b40-4ebe-aa05-f17994007cae)

**Comment by jaesuny** [comment]
https://github.com/vllm-project/vllm/issues/129#issuecomment-1805088950
> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

**Comment by fxrhhx** [comment]
i also have this problem

**Comment by eigen2017** [comment]
same issue for me, any idears?

**Comment by 1E04** [comment]
> same issue for me, any idears?
> 
> driver: 12.2 nvcc: 11.8

Yeah, faced the same problem. If you on Linux and maybe Ubuntu:

1. Uninstall Cuda Toolkit:
`sudo apt-get purge nvidia-cuda-toolkit`

2. Checking Cuda Version for Nvidia Drivers:
 `nvidia-smi`

3. Then search for the toolkit which matches the Cuda Version for your Driver:
https://developer.nvidia.com/cuda-12-2-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local --> for Cuda Toolkit 12.2

4. I used the runfile because it open a little window where you can unselect to Install the Driver again. Download the run-File with:
`wget https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda_12.2.0_535.54.03_linux.run`

5. Run the file:
`sudo sh cuda_12.2.0_535.54.03_linux.run`

6. Follow the CLI and unselect the Driver Installation and Enter on Install.

![grafik](https://github.com/vllm-project/vllm/assets/98465076/f75dfc86-7b3e-4e72-a2cd-3becbd679b15)

8. Add Cuda to PATH
9. Open `vim ~/.bashrc` or any preffered editor.
10. Copy both rows in the bashrc file 
**export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}**
**export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}**
11. Reload  with `~/.bashrc`
12. Check if Cuda Toolkit installed successfully:
`nvcc -V`

**Comment by BramVanroy** [comment]
Duplicate: https://github.com/vllm-project/vllm/issues/1453

**Comment by MMOCKING** [comment]
> [#129 (comment)](https://github.com/vllm-project/vllm/issues/129#issuecomment-1805088950)
> 
> > Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

Thank you so much!!!!!!!!!!!
