### ISSUE TITLE
Question: Why is `memory_efficient_attention_forward` used in PagedAttention?

### ISSUE THREAD

**Issue by EricLBuehler** [vllm-project/vllm#1895]
Hello everybody,

During my development of [candle-vllm](https://github.com/EricLBuehler/candle-vllm), I am implementing PagedAttention based on the implementation here. However, I noticed that in the `.forward` method, a [call to `xops.memory_efficient_attention_forward`](https://github.com/vllm-project/vllm/blob/f86bd6190ad300051fce5f0a13ba03b29e5e199a/vllm/model_executor/layers/attention.py#L156C24-L156C58) is made if the input is a prompt.

Can this be substituted for a "normal" attention? Thanks!

**Comment by WoosukKwon** [comment]
Yes, it is a "normal" attention used in the prefill phase (i.e., when the inputs are prompts). In this case, we don't have to use the KV cache. We can just directly compute attention on the incoming key and value tensors (in the contiguous space) using the existing libraries. We originally used `flash-attn` for this, but moved to xformers since it covers wider range of hardware. While PyTorch's SDPA can also be used here, we didn't choose it because it currently does not support sliding window attention, which is used for Mistral.

**Comment by EricLBuehler** [comment]
Thanks for the clarification!

**Comment by yhyu13** [comment]
@WoosukKwon 

Is there still a way to turn back using flash-attn for CUDA specifically, which commits does the flash_attn->xformer thing? Thanks!

> Yes, it is a "normal" attention used in the prefill phase (i.e., when the inputs are prompts). In this case, we don't have to use the KV cache. We can just directly compute attention on the incoming key and value tensors (in the contiguous space) using the existing libraries. We originally used `flash-attn` for this, but moved to xformers since it covers wider range of hardware. While PyTorch's SDPA can also be used here, we didn't choose it because it currently does not support sliding window attention, which is used for Mistral.
