### ISSUE TITLE
Add a Lit-llama example

### ISSUE THREAD

**Issue by tchaton** [vllm-project/vllm#215]
Hey, awesome project !

Do you have any plans to support Lit-LLama: https://github.com/Lightning-AI/lit-llama

This codebase is optimised for readability and speed, built on top of nano-gpt.

Would be great for learning purposes.

Best

**Comment by zhuohan123** [comment]
If I understand correctly, `lit-llama` is a LLaMA training/inference library instead of a specific model. Currently we have our own implementation of LLaMA with PagedAttention. We will evaluate whether we can import some good optimizations from `lit-llama`.

Thanks for the info about the library. If there is any other questions, feel free to re-open the issue.
