### ISSUE TITLE
worse text generation

### ISSUE THREAD

**Issue by al-becker** [vllm-project/vllm#219]
first of all thanks for releasing the awesome library.

The output texts seem significantly worse compared to huggingface transformers. Could this be an issue with the tokenizer? Any other ideas?

I dont know if it is relevant, but the prompts I am trying are in german and not english.

**Comment by zhuohan123** [comment]
Thanks for reporting the issue. We have tested that all the models are numerically the same as the Huggingface models. If you see drastically worse outputs, it's indeed typically due to tokenizers. You can try to change a tokenizer by modifying the `get_tokenizer` function in `vllm/engine/tokenizer_utils.py`. If you still see worse results, please share the model with us and we can take a look.

**Comment by al-becker** [comment]
I am using vicuna-13b-v1.3. I checked the tokenizers and the tokens are identical. Upon further investigation it might have just been my temperature setting.
