### ISSUE TITLE
performance and concurrency questions

### ISSUE THREAD

**Issue by jtoy** [vllm-project/vllm#2308]
I've done some experiments with vllm and read through the docs, but have not been able to get higher performing systems.
I have a couple of questions.
1) Will using vllm on linux with a 4090 get faster results? I have been comparing with ollama and the speed is the same.

2) will I get automatic speed ups if I use the api web server vs offline batch inference? I did my initial experiments with offline batch inference doing only a single prompt at a time, and saw no speed difference. My current code does single llm requests at a time, not in batches.

3) to properly properly use vllm , do I need to convert my code to be concurrent/send batch requests?

**Comment by rsnm2** [comment]
The primary value-adds of vLLM are:
- Paged Attention --> a careful implementation of KV caching which enables you to serve more concurrent requests per device in an API Server (as the primary bottleneck capping the number of requests is KV cache memory)
- Tensor Parallel Model Implementations --> performant inference-only implementations of models which shard the model over GPUs enabling a speedup (and more batching, since we can fit more kv caches if the model is sharded rather than replicated across GPUs)

^ these ideas are primarily useful for an INFERENCE SERVER which serves multiple users / handles multiple concurrent requests.

In addition, vLLM curates performant CUDA-kernels (e.g. flashattention, gptq+awq+squeeze llm quantized kernels), builds some of their own CUDA-kernels (e.g. rotary embeddings, silu_and_mul activation function), and builds some more performant implementations of the models (such as vectorized sampling, and single qkv_proj / up_gate_proj) which should help performance.

^ as a result, vLLM can be faster relative to a naive HF Transformers reference implementation of LLMs which does not use any of these tricks. However, some of the tricks targeted at offline, single-gpu, single-user inference are less "unique" to vLLM (and though I'm not familiar with ollama, I would expect other libraries targeting performance would do the same. vLLM is a perfectly good choice and performant for this use case.


Separately, if you are running offline inference, you will be able to run much faster if you do batched execution. LLMs are very very very memory bound at b=1, so you will see significant increases in throughput by running at higher batch sizes. In this case, vLLM will be very helpful.

**Comment by jtoy** [comment]
Thanks for detailed notes. I guess my question is, how do I get anything similar to what is posted on their pages:
https://blog.vllm.ai/2023/06/20/vllm.html

"In our experiments, vLLM achieves up to 24x higher throughput compared to HF and up to 3.5x higher throughput than TGI."
"Serving throughput when each request asks for three parallel output completions. vLLM achieves 8.5x - 15x higher throughput than HF and 3.3x - 3.5x higher throughput than TGI. "

Can any of that be achieved with a 4090 ? I see in their examples they use an  NVIDIA A10G GPU

**Comment by Lvjinhong** [comment]
Hi，I tested that when the gpu_memory_utilization is set to 0.9, the performance approaches its limit. When set higher, for example, to 0.95, there is no significant increase in throughput; instead, there's a slight decrease. But why?

**Comment by rsnm2** [comment]
@jtoy That blog is from 6 months ago. Important to keep in mind that other frameworks are incorporating ideas from vLLM. For instance, Hugging Face TGI now literally uses the PagedAttention kernels from vLLM (not the same idea, literally the kernels). 

https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/paged_attention.py

At the time of the blog, vLLM was ~2x faster than TGI for a single generation per prompt. In cases where there was multiple generations per prompt (i.e. beam search), the difference would be greater (i.e. the ~3.5x they quoted). I do not know what the performance comparison is now. You can see the numbers for this right in the first chart on the blog...

As I said in my original comment, vLLM will be much faster than naive HF transformers, which is consistent with their original blog.

I have no idea what optimizations ollama implements so I cant comment on whether vLLM should be faster or slower. My sense is that ollama is targeted at local inference rather than an inference server with multiple concurrent users, but Im really not sure.

The point still holds that vLLM is a performant local inference option for 1gpu / 1user (but is not super unique at this), but shines best in a multi-gpu/1user, multiple user scenario.

**Comment by jtoy** [comment]
coming back to this, I have access to multiple servers now,1 with 8 1080'ss and 1 with 8 L40s's . My preliminary tests is that ollama can't actually utilize all GPUs. I would love to be proven wrong. If I want concurrency to work for models like mistral, what is the best solution to use?

**Comment by isaac47** [comment]
@jtoy Can you please details how to you made your tests? I have the same issue and the solution is to create multiple instance and a proxy to select which instance will be use. 

I also find the best solution to manage multi users. Can you have others things to share?

**Comment by hmellor** [comment]
Closing as stale.
