### ISSUE TITLE
GPU utilization decrease during long-term running

### ISSUE THREAD

**Issue by WrRan** [vllm-project/vllm#2556]
When using vLLM for offline batch prediction, I found a significant decrease in GPU utilization during long-term running. As shown in the graph below, the utilization rate is around 60-70% at 00:00, but it drops to 50-60% by 15:00. What could be the reason for this? Is there a plan to fix it?
<img width="687" alt="image" src="https://github.com/vllm-project/vllm/assets/7569098/cbe0199a-ea9c-4e85-8143-7f5dd4985a79">

Currently, I suspect that there are too many GPU memory fragments, and I am trying to alleviate this problem by periodically restarting the system.

**Comment by su-park** [comment]
@WrRan 

Hello.
I am reaching out because I am experiencing a similar situation.
I am conducting long-term inference in a multi GPU (8 units) environment.
At some point, the GPU utilization drops, causing the inference to be delayed with 2 units at 100%, and the rest at 0%.
If you had a similar issue, could you please tell me how you resolved it?

**Comment by hillarysanders** [comment]
Anyone understand why this is happening? cc @WrRan was your issue resolved somehow?

**Comment by WrRan** [comment]
@hillarysanders @su-park 

I alleviate this problem by periodically restarting the system.

**Comment by wanghia** [comment]
I meet same problem. The GPU utilization is fluctuating greatly, with an average utilization of only 50%, but there are still pending requests.
