### ISSUE TITLE
[BUG] Quantization support for MoE models

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2663]
After #2453 and #2542, the new fused MoE kernel used in Mixtral and DeepSeek-MoE does not support quantization.

**Comment by AlpinDale** [comment]
An easy, but hacky, solution would be to fall back to the old MoE code if quantized linear methods are detected. Unquantized models can use the new kernels.

**Comment by casper-hansen** [comment]
I was looking to import the MoE Triton kernel to AutoAWQ.

I was looking at two solutions:
1. Dequantize before using Triton kernel. Requires some implementation details since `nn.Parameter` is used with multiple experts. Unsure if you can loop over the experts and if it would be slow.
2. Implement dequantization in the MoE Triton kernel from @WoosukKwon's [`qmm` branch](https://github.com/vllm-project/vllm/tree/qmm).

Both introduce some complexity. I would prefer the second one for performance reasons though.
