### ISSUE TITLE
Cannot get expected model size reducing when lauching squeezellm mode

### ISSUE THREAD

**Issue by ykacer** [vllm-project/vllm#2786]
Hi Everybody,

I'm simply following vllm (version **0.3.0**) helper to run a squeezellm quantized llama-2 model, using following command 

`python3 -m vllm.entrypoints.openai.api_server --model squeeze-ai-lab/sq-llama-2-7b-w4-s0 --tensor-parallel-size 1 --max-model-len 1000 --gpu-memory-utilization 0.9 --quantization squeezellm`

It runs well but  `nvidia-smi` show that model is occupying **~15Gb** among the 16Gb available in my NVIDIA V100, while i expected model size to be reduced by 4.
Is there something i did wrong? Does my GPU fit with squeezellm quantization requirements? Or maybe my environement has not been built the right way?

Thanks for any help or any link that show successful use of llama-2 with squeezellm

Regards

**Comment by WoosukKwon** [comment]
Hi @ykacer, vLLM pre-allocates the GPU memory for KV cache at the initialization time. In your case, it occupies roughly 90% of your total GPU memory since `gpu-memory-utilization` is 0.9. You can control this value to limit vLLM's GPU memory usage while higher values enables larger maximum batch size and thus leads to higher throughput.
