### ISSUE TITLE
model continue conversation 

### ISSUE THREAD

**Issue by andrey-genpracc** [vllm-project/vllm#2789]
Hi!

I have additional ###Instruction: and ###Response: 
for this instruction from model. 

I mean that model continues conversation and add additional Instruction and after that response on this instruction
I use vllm alpaca.template  for model : https://huggingface.co/TheBloke/MLewd-ReMM-L2-Chat-20B-AWQ . In model card described this type of template 

I tried to use  ###Instruction: in stop attribute but it doesn't help me to solve problem

**Comment by hmellor** [comment]
It appears that your model has an instruct style prompt template rather than a chat style prompt template. Unfortunately, some models that were trained for instruct prompts (which this one appears to be) do not transfer well to chat templates.

This is an issue with the model you are using, not an issue with vLLM.
