### ISSUE TITLE
[feature request] consider integrate the QUICK kernel for AWQ quantization

### ISSUE THREAD

**Issue by sighingnow** [vllm-project/vllm#2920]
QUICK: https://github.com/SqueezeBits/QUICK/tree/main

**Comment by casper-hansen** [comment]
It seems the authors already have an implementation in vLLM. @JHLEE17 and @tae-su-kim, do you plan to upstream a pull request to vLLM?

From the [QUICK README](https://github.com/SqueezeBits/QUICK):

> Throughput was evaluated using the [benchmark_throughput](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py) script within vLLM.

**Comment by tae-su-kim** [comment]
Hello vLLM community, yes we're planning to pile a PR soon (hopefully within a week).
Currently we have a very hacky version of vLLM integration - mostly because of the pre-fused layers such as qkv and up_proj. We will figure out better ways to handle those, and upstream our PR.

**Comment by shiqingzhangCSU** [comment]
> Hello vLLM community, yes we're planning to pile a PR soon (hopefully within a week). Currently we have a very hacky version of vLLM integration - mostly because of the pre-fused layers such as qkv and up_proj. We will figure out better ways to handle those, and upstream our PR.

Great job, can there be a branch where we can pull it?

**Comment by darrenglow** [comment]
> Hello vLLM community, yes we're planning to pile a PR soon (hopefully within a week). Currently we have a very hacky version of vLLM integration - mostly because of the pre-fused layers such as qkv and up_proj. We will figure out better ways to handle those, and upstream our PR.

Hi, @tae-su-kim , is there any progress on this?

**Comment by tae-su-kim** [comment]
Hi @darrenglow, sorry for the huge delay. Our PoC is available on the fork here:
https://github.com/SqueezeBits/vllm-quick/tree/vllm-quick

Since the weight packing pattern does not allow simple concatenation along channel dimension for the layer fusion (such as QKV, gate_up), current version applies some hacky workaround to hf_model_weights_iterator function. We'll definitely have to re-work this to make our fork meet deploy-level-quality.

Yet it works; Please feel free to explore and give us some hints, if any, to land this feature in elegant way. Thanks!!
