### ISSUE TITLE
The answer accuracy of the QWen series model is lost

### ISSUE THREAD

**Issue by zhochengbiao** [vllm-project/vllm#2952]
After using Vllm acceleration on the QWen series model, there is a significant loss in the accuracy of answers

**Comment by whyiug** [comment]
try to update the eos token to <|im_end|> in tokenizer_config.json

**Comment by ArlanCooper** [comment]
+ 1 ,how to solve this problem?

**Comment by ArlanCooper** [comment]
> try to update the eos token to <|im_end|> in tokenizer_config.json
i set it ,but the answer is still wrong.

**Comment by GeraldWu23** [comment]
I tried and still get wrong answer. To be specific the model seem to  ignore the eos in my ft(<|im_end|>). I suppose it's not the problem of the tokenizer, because when I put the target answer and the <|im_end|> to the end of the input, it doesnt stop generating.
![image](https://github.com/vllm-project/vllm/assets/27190172/4280d1ea-1dce-425c-bc0f-747fe1135c53)

I have already manally set bos, eos, and pad token according to all config files in the model. The model work well without vllm, and generate <|im_end|> properly to stop generating.

Is it the same to your case, and would be nice if anyone solved this issue

**Comment by GeraldWu23** [comment]
A bit update of this case. Vllm wraps tokenizer and model with engine, so you need to update tokenizer and model in engine of vllm when using vllm, which is not exactly the same as when we were not using vllm. It solves my problem in this way. If you still get problem, check special tokens of your tokenizer and model in your vllm engine.
