### ISSUE TITLE
Is there a mecanism of priorities when sending a new request 

### ISSUE THREAD

**Issue by brunorigal** [vllm-project/vllm#3058]
The goal would be to get faster answers for some requests than others, it could be handled by a priority queue feeding the engine, but I could not find such a thing.

**Comment by schoennenbeck** [comment]
There already is somewhat of a priority mechanism in the scheduler for the `LLMEngine` (see [policy.py](https://github.com/vllm-project/vllm/blob/main/vllm/core/policy.py) and [scheduler.py](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py)). However, the only policy available at the moment is "fcfs" (first come first serve) and moreover the waiting sequences are not sorted since they are added in order of arrival which fits with only doing fcfs. 

I have played around a little adding a policy where you can provide the priority via an extended version of `SamplingParams`:

```python
class SamplingPriority(Policy):
    def get_priority(self, now: float, seq_group: SequenceGroup) -> tuple[float, float]:  # type: ignore[override] # Policy only needs the return type to be sortable
        # You should use an extended SamplingParams-class that has a property 'priority'
        return (
            getattr(seq_group.sampling_params, "priority", 1),
            now - seq_group.metrics.arrival_time,
        )
```

(this would work the other way around compared to a `PriorityQueue`, i.e. a higher number for priorty should mean that a sequence is handled earlier).

However, this has no apparent influence on the order in which sequences are handled - even if I make the scheduler sort the `waiting`, `running` and `swapped` deques. And I don't yet understand the scheduling logic well enough to figure out what's going on. Moreover, there seems to be a major rewrite in the scheduling logic in [scheduler.py](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py) compared to [scheduler.py (v0.4.0)](https://github.com/vllm-project/vllm/blob/v0.4.0/vllm/core/scheduler.py) so I am not to keen to invest the time to understand it now.

**Comment by schoennenbeck** [comment]
Okay here is what you can do:

- Give the `sampling_params` in your requests a property `priority` (higher means earlier handling)
- Set `engine.scheduler.policy = SamplingPriority()` (where `engine` is an `LLMEngine`, if you are using `AsyncLLMEngine` do `engine.engine.scheduler.policy = ...`
- Finally:
```python
def add_seq_group(scheduler: Scheduler, seq_group: SequenceGroup) -> None:
        scheduler.waiting.append(seq_group)
        scheduler.waiting = scheduler.policy.sort_by_priority(now, scheduler.waiting)

engine.scheduler.add_seq_group = add_seq_group
# or (if your engine is an AsyncLLMEngine)
engine.engine.scheduler.add_seq_group = add_seq_group
```

What this will do:
High priority requests are moved to the front of the waiting queue. So the next time there is a slot available for a sequence to be handled these requests are prefered. This does not, however, lead to new high priority requests taking precedence over already running low priority requests. Implementing that would require a significantly more work by my guess.
