### ISSUE TITLE
There is a error in output text. but output's token_ids is right.

### ISSUE THREAD

**Issue by snakecy** [vllm-project/vllm#3131]
maybe the error happend in the file detokenize_incrementally.py 

the fuc is : 

from vllm import LLM

model = LLM('*')
response = model.generate('xxxxx')

the result response.outputs[0].text will be truncationed. but the .tokens_ids is right.

```
version: 
vllm: 0.3.1
torch:2.1.2
cuda:11.8
```

**Comment by rechjq** [comment]
me too

**Comment by rechjq** [comment]
vllm: 0.3.2

**Comment by shallinan1** [comment]
+1

**Comment by mpoemsl** [comment]
I know this is an old issue, but just wanted to note I encountered a similar issue. In my case, it was because of the `include_stop_str_in_output` logic [here](https://github.com/vllm-project/vllm/blob/96846bb3607370798540c7d325f8d06dbd67dcf4/vllm/v1/engine/detokenizer.py#L78). Using `stop_ids` instead of `stop` helped.
