### ISSUE TITLE
[bug] EngineArgs( TypeError: EngineArgs.__init__() got an unexpected keyword argument 'ray_workers_use_nsight

### ISSUE THREAD

**Issue by MrRace** [vllm-project/vllm#3249]
```
python3 -c "import vllm; print(vllm.__version__)"
0.3.3
```

when use `benchmarks/benchmark_latency.py` comes error:
```
File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 91, in __init__
    engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'ray_workers_use_nsight'
```

when use `benchmarks/benchmark_throughput.py` comes error:
```
File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 91, in __init__
    engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'enable_prefix_caching'
```

**Comment by justin225** [comment]
+1

**Comment by pcmoritz** [comment]
This is most likely because you are running `benchmarks/benchmark_throughput.py` from master against the `0.3.3` release of vllm -- you need to run the version from `0.3.3` against that version since these flags were added recently. You can find the version in 

https://github.com/vllm-project/vllm/blob/82091b864af105dbe373353655dc9d8c0a6ba66f/benchmarks/benchmark_latency.py

(I got the commit from https://github.com/vllm-project/vllm/releases and then clicking on the 0.3.3 release)

**Comment by pcmoritz** [comment]
I'll close this now, please reopen if it still doesn't work :)
