### ISSUE TITLE
Cannot server StarCoder 2 with `vllm/vllm-openai:v0.3.3` image?

### ISSUE THREAD

**Issue by andyl98** [vllm-project/vllm#3325]
Hi all,

When I was trying to test the newly released StarCoder2 model with 0.3.3, I noticed the following error being thrown:
```ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.```

From my understanding this is due to `transformers` not releasing support for SC2 in the current released version but only in the master branch? Lmk if I am understanding correctly, and if so, is there anyway to fix the image? Thanks!

**Comment by andyl98** [comment]
Maybe `transformers >= 4.38.0  # Required for Gemma.` from the `requirements.txt` is not enough?

**Comment by esmeetu** [comment]
@andyl98 Make sure your model name or path contain `bigcode` and `starcoder2` string. And We will remove this temporary check after `transformers` support `startcoder2`.

**Comment by jing-P** [comment]
local starcoder2 path is "/home/models/bigcode/startcoder2-15b/", the error occured:【ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.】

**Comment by rkooo567** [comment]
Actually this issue seems to happen in our CI right now

**Comment by jfpichlme** [comment]
any updates?
