### ISSUE TITLE
Task finished unexpectedly. This should never happen! Please open an issue on Github.

### ISSUE THREAD

**Issue by mkhludnev** [vllm-project/vllm#3407]
Hello 
I run 34B AWQ model on two A2 - `--tensor-parallel-size 2`. 
VRAM usage for both `14198MiB / 15356MiB`.
I occurs from time to time on long requests: 
```
uture exception was never retrieved
future: <Future finished exception=OutOfMemoryError('CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacty of 14.54 GiB of which 60.94 MiB is free. Process 868956 has 14.47 GiB memory in use. Of the allocated memory 12.85 GiB is allocated by PyTorch, and 391.40 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 29, in _raise_exception_on_finish
    task.result()

Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7fdaecb5edd0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fdaea3d7b20>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7fdaecb5edd0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fdaea3d7b20>)>

  File "/workspace/vllm/engine/async_llm_engine.py", line 33, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
``` 

But then, one request seems stuck and spins infinitely fully consuming CPU - 100% and one of GPUs also 100% 

```
INFO 03-04 14:42:13 metrics.py:161] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.8%, CPU KV cache usage: 0.0%
```
Restart seem helps

Which direction I need to follow? 
Error mentions some CUDA memory params, also vllm log also mention something about eager-something param, Can twearing one of these help to resolve this error?

**Comment by rkooo567** [comment]
So, I think there are 2 issues here. 

> vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

This error message is really sketchy, and I feel like you touched the edge case. Is there a way to repro this issue?

The second issue is your request failed because of VRAM OOM. `enforce_eager=True` disables cuda graph. cuda graph requires additional memory since graph needs to be cached in VRAM.  This can reduce memory usage a bit, but it will also impact performance. 

Alternatively, you can probably use lower values for `gpu_memory_utilization`. This is 0.90 by default, and if you specify the lower value, it will do less preallocation of GPU blocks (so I think it will leave you some more VRAM)

**Comment by mkhludnev** [comment]
[log.txt](https://github.com/vllm-project/vllm/files/14613237/log.txt)
@rkooo567 It's hard to reproduce since it seems like caused some long request. I can share full error log here^

**Comment by rkooo567** [comment]
Okay, I took a look at this a little bit, and it seems like the server itself is really fragile to any failures. I.e., if any failures happen to the server, it crashes like this, and in your case, it is due to GPU OOM error.

- Use higher tensor parallel (ScalingConfig.num_workers) to reduce per GPU mem usage.
- Use lower gpu_utilization (which will reserve less KV caches) so that you will have more space for long prompts

@simon-mo, please add comments if you know more techniques!

Also, is this on the roadmap to improve async server stability? (imo, server should survive from failures, but Idk if the it is by design). For your case, I think the best way to fix is to make sure you don't have GPU OOM. I think there are some options;

**Comment by Yard1** [comment]
"Task finished unexpectedly. This should never happen!" is a generic issue, and as it says, the actual cause should be printed in the stack trace above. 

If the server is misconfigured, it should crash during initialization. Otherwise, we should aim for no crashes during runtime. However, should we enter an unexpected state, in many cases it is better to force a full restart than try to try to recover IMO. With things like NCCL it's hard to guarantee correct recovery.

**Comment by rkooo567** [comment]
@Yard1 so the recommended solution is to handle this in a higher layer? For our internal use case, https://github.com/ray-project/ray-llm handles restart right?

**Comment by Yard1** [comment]
Yes that's correct, fault tolerance (in this case restarting) should be handled on a higher level and indeed rayllm will do that.

However if there are bugs/oversights in vLLM that cause errors to be thrown during runtime (like here) they should obviously be fixed.

**Comment by rkooo567** [comment]
Yeah crashing on any exception (status quo) seems pretty harsh

**Comment by Yard1** [comment]
We should just ensure those exceptions do not happen in the first place

**Comment by mkhludnev** [comment]
> the actual cause should be printed in the stack trace above (which would be helpful to provide!)

Sure. Here we go. https://github.com/vllm-project/vllm/files/14613237/log.txt

**Comment by Yard1** [comment]
Yeah, looks like that's an OOM. Reducing `gpu_memory_utilization` could help.
