### ISSUE TITLE
[Installation]:  Tesla V100 cuda11.4, I have no permission to install a upper-version cuda driver, how can I install vllm? I have tried to build from source and use pip, both failed.

### ISSUE THREAD

**Issue by LaVieEnRose365** [vllm-project/vllm#3812]
### Your current environment

Tesla V100, cuda11.4

### How you are installing vllm

```sh
pip install vllm
```

**Comment by robertgshaw2-neuralmagic** [comment]
I believe you need at least CUDA 11.8 to build vLLM

cc @youkaichao

**Comment by youkaichao** [comment]
Sorry but we cannot do anything in this case :( You need a decently new cudatoolkit and driver to build vLLM from source, or have cuda 11.8/12.1 so that you can use our pre-built wheels.

**Comment by geekchen007** [comment]
> Sorry but we cannot do anything in this case :( You need a decently new cudatoolkit and driver to build vLLM from source, or have cuda 11.8/12.1 so that you can use our pre-built wheels.

"I noticed that the mainstream support for VLLM in the git repository is for CUDA 11.8 and CUDA 12.x, but the CUDA version on my machine is 11.4. It's difficult to upgrade due to other reasons. I'm wondering if there are any good solutions that can allow me to use VLLM with this older CUDA version."

**Comment by xiaoyaguang** [comment]
Hi, have you resolved this issue? I’m encountering the same problem.
