### ISSUE TITLE
pip install error with missing libcupti.so.11.7

### ISSUE THREAD

**Issue by xyw0078** [vllm-project/vllm#384]
Hi, 

My environment has cuda 11.8 (linux), but the pip installation gives the following error while building the wheel:
`libcupti.so.11.7: cannot open shared object file: No such file or directory`
It seems that the installation is looking for cuda 11.7 specifically for some reason.
Any insight on this one?

Many thanks

**Comment by WoosukKwon** [comment]
Hi @xyw0078 Thanks for trying out vLLM! vLLM identifies the CUDA version by parsing the output of `nvcc -V`. So, could you run `nvcc -V` in your terminal and share the output?

**Comment by xyw0078** [comment]
> 
Here is the cuda version: `Cuda compilation tools, release 11.8, V11.8.89 `

My friend also found a work around for this issue, ill quote his findings here:

"clone vllm and copy the repo to your pod, and remove pyproject.toml, and run pip install ."

"pyproject.toml will create virtual env for installation for setup.py, however, pytorch only offers torch compiled with 11.7 for default setting and virtual env uses pytorch with cu 117, not preinstalled version."

Hope this helps.

**Comment by cartopy** [comment]
Hello I'm a co-worker for @xyw0078 , I also checked `nvcc -V`, however, it still shows cuda 11.8.

After some investigation, I realized that using `pyproject.toml` will create virtual env with pep 517 for vllm installation, and the venv doesn't use our preinstalled pytorch compiled for CUDA Toolkit 11.8. The venv is trying to use a default pytorch version 2.0.0 compiled for CUDA Toolkit 11.7.

I'm aware of that a default pytorch is also self-contained for CUDA, however, somehow, the configuration seems conflicted in our docker environment. 

So, my solution is to disable pep 517 mode installation by removing pyproject.toml in order to use preinstalled pytorch with cuda 11.8. Then, `pip install .` successfully installs vllm.

Could you let us know whether this approach will create any other possible issue?

Thanks,

**Comment by creatorrr** [comment]
Ran into this before. Setting the correct `LD_LIBRARY_PATH` should fix it.

**Comment by cartopy** [comment]
@creatorrr It's correctly set up.`/usr/local/cuda/lib64:`

**Comment by creatorrr** [comment]
Gotcha. Try upgrading torch to the nightly version

**Comment by Praful932** [comment]
I also faced a similar issue, poetry attempts to install a different version of torch even when i have specified an URL for the 11.8 compiled torch .whl file. 
Temporarily worked around this by running vanilla `pip install` once i figured out all of the dependencies for my env

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
