### ISSUE TITLE
[Feature]: PyTorch Labs MoE Kernels (2.7-4.4x faster)

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#3855]
### 🚀 The feature, motivation and pitch

vLLM should adopt the PyTorch Labs Triton kernels that were developed recently since they can yield *2.7x faster for bs=2 and 4.4x for bs=512*. @WoosukKwon Note that the new kernels were developed on top of the existing vLLM kernels, so they should be highly compatible.

Blog: https://pytorch.org/blog/accelerating-moe-model/?utm_content=288416924
Code: https://github.com/pytorch-labs/applied-ai/tree/main/kernels/triton/inference/col_major_moe_gemm

![image](https://github.com/vllm-project/vllm/assets/27340033/eb99d7be-2470-47fe-88df-9ed608f84377)

**Comment by WoosukKwon** [comment]
@casper-hansen Thanks for bringing this up! We will reach out to the IBM folks whether they are interested in the integration.

**Comment by njhill** [comment]
Amazing work by @AdnanHoque @ani300 @cyang49 from IBM Research! They will be contributing this back to vLLM soon!

**Comment by AdnanHoque** [comment]
Great work on the MoE kernel Woosuk! Learned a lot studying it :) 

We haven't done much end-to-end testing but due to things like tl.atomic_add() not supporting bfloat16 etc. these kernels may not end up something we end up contributing. 

I have been working on fusing dequantization into the MoE kernel to allow for a W4A16 GPTQ path, would be great to collaborate on that front if it's something you've been looking to add!

W4A16 Fused MoE: [https://github.com/pytorch-labs/applied-ai/blob/main/kernels/triton/inference/gptq/mixtral/w4a16_fused_dequant_gemm.py](https://github.com/pytorch-labs/applied-ai/blob/main/kernels/triton/inference/gptq/mixtral/w4a16_fused_dequant_gemm.py)

**Comment by robertgshaw2-neuralmagic** [comment]
https://github.com/vllm-project/vllm/pull/3905

there appear to be some correctness issues with these kernels that we need to debug
