### ISSUE TITLE
[Misc]: Does prefix caching work together with multi lora?

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#3958]
### Anything you want to discuss about vllm.

Can I enable prefix caching to improve performance when using multiple lora ?

**Comment by jeejeelee** [comment]
Yep

**Comment by sleepwalker2017** [comment]
> Yep

Thank you!

**Comment by curiositywan** [comment]
> Yep

Hello, not sure if this is related.

https://github.com/vllm-project/vllm/issues/5475

I recently encountered an issue using prefix caching for multi lora setup. From my profiling, it looks like switching lora heads will cause some performance degradation, not sure if it is because of my setup or some bugs in vllm.
