### ISSUE TITLE
[Misc]: Add sanity test on Python 3.8

### ISSUE THREAD

**Issue by rkooo567** [vllm-project/vllm#4099]
### Anything you want to discuss about vllm.

Currently, CI only runs on Python 3.9. For Python > 3.9, there's no problem with this approach because Python guarantees the backward compatibility, but Python 3.8 (which is still the version that's supported) is not properly tested and sometimes caused issue like https://github.com/vllm-project/vllm/pull/4092#issuecomment-2057867553

To solve this issue, we can have a simple sanity check test on Python 3.8.

**Comment by simon-mo** [comment]
1. The fact that github action did catch this with our mypy x 3.8 matrix means we have to run the code the test.
2. This means, we need to run test with Python 3.8. This probably requires parameterize the Dockerfile to install 3.8 from the base image. 
3. Notably we tried this before but we want to keep latest Python release for final delivery because newer Python version have higher performance.

**Comment by DarkLight1337** [comment]
Closing since pytorch 2.5 doesn't support python 3.8 anymore.
