### ISSUE TITLE
[Feature]: No `outlines` strong dependency

### ISSUE THREAD

**Issue by Theodotus1243** [vllm-project/vllm#4153]
### 🚀 The feature, motivation and pitch

https://github.com/vllm-project/vllm/blob/main/requirements-common.txt

Here vllm has `outlines == 0.0.34`
But starting from [v0.0.38](https://github.com/outlines-dev/outlines/releases/tag/0.0.38) outlines has VLLM integration https://github.com/outlines-dev/outlines/pull/772

But I can't update to latest vllm to use it, as it rises versioning error
This error can be ignored
But can somehow this be resolved?

**Comment by simon-mo** [comment]
Is this a circular dependency/versioning/dependency hell issue?

**Comment by simon-mo** [comment]
Hopefully #4109 will allow us to unpin outlines

**Comment by he-yufeng** [comment]
Store-side follow-up to the connector probes above. I audited the read path on the Mooncake store at current main (ffe01351), because that is the layer the contamination has to come from once the connector is clean.

What is guarded:

- Every memory-resident read path carries the master read lease: `GetReplicaList` grants a 10s lease by default (`DEFAULT_DEFAULT_KV_LEASE_TTL`, types.h:84), the master eviction loop skips keys with unexpired leases, and the client converts a read that outlived its lease into a loud `LEASE_EXPIRED` after the transfer (`client_service.cpp:1377`, `:1422`, `:1576`, `:1826`). Within the lease a memory replica cannot be evicted, past the lease the read fails loudly. No silent window there.

What is not guarded:

- The connector loads through `batch_get_into_multi_buffers`. Its MEMORY/NOF and DISK/DFS sub-paths delegate to the guarded `Client::BatchGet`, but LOCAL_DISK (SSD offload) replicas go through the offload RPC branch (`real_client.cpp:6477` -> `:6510` -> `:6772`) which has no master read-lease check at all. The only guards on that branch are the offload-side `gc_ttl` elapsed check (`:7413`, and only when the batch is not node-local) and the optional object CRC behind `MOONCAKE_STORE_CHECKSUM` (`environ.cpp:204`, default off).

So in an offload-enabled deployment under eviction churn (your 92% full pool with 22/1217 evicted), an offload read that outlives its 10s master lease, or that races an eviction plus backing-slot reuse, can complete as success with bytes that no longer belong to the key, and nothing on that path would notice. That is the only silent channel I have found that matches the symptom (attention sinks plus garbage inside the shared prefix region).

Three data points would confirm or kill this theory from your side:

1. Is the deployment running with SSD offload enabled, and with what `client_buffer_gc_ttl_ms`?
2. Do the worker logs contain `lease_expired_before_data_transfer_completed` or `OBJECT_HAS_LEASE` warnings around the incident window? Their absence on a memory-resident read would itself be evidence the reads went through the offload branch.
3. Is `MOONCAKE_STORE_CHECKSUM` set? If it is off (the default), the last safety net on the offload path is also down.

On my side I am now probing the last link: whether the offload file storage reuses a freed object slot for a different key's bytes while a read of the old object is still in flight. Will report back with a synthetic slow-read race probe.

(This analysis was assisted by Kimi K3; all cited lines were re-read and verified on the pinned commits.)
