### ISSUE TITLE
A matching Triton is not available, some optimizations will not be enabled.

### ISSUE THREAD

**Issue by Hukongtao** [vllm-project/vllm#424]
Why is this paragraph printed in the output log? How to fix it?   
![image](https://github.com/vllm-project/vllm/assets/16505966/3e07d7d6-0fb5-4cd4-8c53-6cde368eb1c6)

**Comment by WoosukKwon** [comment]
Hi @Hukongtao, thanks for trying out vLLM! It's because vLLM uses [xformers](https://github.com/facebookresearch/xformers), which includes Triton implementation of flash attention as one of its backend. However, vLLM only uses its CUTLASS backend. So, it should be ok to just ignore the warning message.
