### ISSUE TITLE
does tensor parallell support model parallelism?

### ISSUE THREAD

**Issue by notphantasy** [vllm-project/vllm#466]
for example if i have a model that is too big to fit into one GPU, if i do tensor-parallel=X would that let me load the model across multiple GPUs?

**Comment by WoosukKwon** [comment]
Hi @notphantasy, thanks for the question. Yes, tensor parallelism allows you to shard your model across GPUs so that you can run large models that do not fit into a single GPU. Please check out [our document](https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html#distributed-inference-and-serving) on how to enable tensor parallelism in vLLM.

**Comment by notphantasy** [comment]
trying to do this on a dual 3090 setup and getting a P2P error. not sure if you're familiar with the hardware but would this require NVlink?
