### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by doudoujay** [vllm-project/vllm#484]
dockerfile:
```
FROM nvcr.io/nvidia/pytorch:22.12-py3
RUN pip uninstall torch -y
RUN pip install vllm
RUN pip install pydantic==1.10.11
RUN pip install fschat
```

The native api server was running fine --
```
python -m vllm.entrypoints.api_server \
--model stabilityai/stablelm-tuned-alpha-7b \
--tensor-parallel-size 2 \
--host 0.0.0.0
```

Openapi server comes with this issue --
```
python -m vllm.entrypoints.openai.api_server \
--model stabilityai/stablelm-tuned-alpha-7b \
--tensor-parallel-size 2 \
--host 0.0.0.0
```

transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so error ^

**Comment by zhuohan123** [comment]
I believe this is an issue introduced by the `accelerate` package as a dependency of fastchat. Can you double-check your trasnformer/accelerate installation?

**Comment by doudoujay** [comment]
@zhuohan123 
i didnt mod any transformer/accelerate installation.
By the way even without 
```
RUN pip install fschat
```
Its causing the same problem with transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so

**Comment by trannhatquy** [comment]
when I use the api to do inference it raises an error: "openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7d8208df0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
Does anyone have the solution for this bug ? Thank you so much

**Comment by v1nc3nt27** [comment]
@doudoujay did you solve the issue?

**Comment by Doohae** [comment]
@trannhatquy have you found any solution?

**Comment by Doohae** [comment]
> > @trannhatquy have you found any solution?
> 
> @Doohae you should add -p 8888:1950 when build docker

Thanks sincerely, I'll try this!
What does exactly happen if I add `-p 8888:1950`?
