### ISSUE TITLE
[Feature]: Support loading of sharded vLLM serialized models with Tensorizer

### ISSUE THREAD

**Issue by tjohnson31415** [vllm-project/vllm#4957]
### 🚀 The feature, motivation and pitch

PR https://github.com/vllm-project/vllm/pull/3476 added support for loading models with Tensorizer, but has the limitation that it does not support loading a sharded vllm-serialized model to multiple GPUs (see [this verification check](https://github.com/vllm-project/vllm/blob/c3af44722cff56bba5fc912c8e16d9de02dfb532/vllm/model_executor/model_loader/tensorizer.py#L81-L87)). Use of sharded models would also benefit from the faster loading and encryption provided by Tensorizer.

[This issue open with Tensorizer](https://github.com/coreweave/tensorizer/issues/81#issuecomment-1935224826) suggests a couple of approaches to support sharding. With tensor-parallel models, the model is split across the GPUs and the suggestion is to serialize each shard separately.

I have prototyped this approach of splitting the vllm-tensorized model into multiple shards and am working on a PR.

### Alternatives

The alternative given in [the Tensorizer issue](https://github.com/coreweave/tensorizer/issues/81#issuecomment-1935224826) is to deserializing Tensors to CPU memory and then send the tensors to the GPUs. This would decouple the serialization of the model from the sharding configuration, but would also be less efficient.

**Comment by tjohnson31415** [comment]
cc: @sangstar I'm curious what your thoughts are on supporting sharded vllm tensorized models and if this is the right approach.

**Comment by sangstar** [comment]
> cc: @sangstar I'm curious what your thoughts are on supporting sharded vllm tensorized models and if this is the right approach.

Eager to see your PR on this! The topic of loading sharded _vLLM serialized models_ is just a matter of Tensorizer supporting sharding, which is a feature we've had lots of discussion on how we'd best like to implement. As you've seen in the issue, it's already feasible to do this with multiple serializers and deserializers, but we haven't rigorously tested or benchmarked this yet, and because of this it's hard to give a definitive answer on what the right approach is, as we're not sure yet.

**Comment by sangstar** [comment]
Working with serialized shards will be performant, but there are a couple of considerations one should make if trying to implement this with `tensorizer`:

- Deserialization incurs a performance cost as the number of shards increase, as apart from competing resources, the buffer setup phase for multiple deserializers can not occur perfectly concurrently (some part of the process are simply not parallelizable). As such `num_shards = num_devices` would be ideal, and the smaller the better.

- Sharded serialization to a certain `num_devices` expects that same `num_devices` during deserialization as the device count is baked into the serialization, so if `num_devices` changes, you'd need to reserialize. 

We have plans to implement this natively with `tensorizer`, but can't speak as to when that would be, although conversations on this matter have been leaning towards a feature that allows direct tensor-device mapping, that we think could be more robust than a multiple file approach. This is due to `tensorizer`'s native parallelism when reading from a single file. We load all the metadata up front, so we would know what devices to load tensors to.

**Comment by tjohnson31415** [comment]
Thank you for the additional context!
Yeah, my current approach requires `num_shards == num_devices` and assumes that the serialization and loading use the same number of devices, but it would be nice to lift that restriction in the future.

Initial PR has been pushed up: https://github.com/vllm-project/vllm/pull/4990

@sangstar I'd appreciate any feedback you have on it. Thanks!
