### ISSUE TITLE
[Usage]: quantization option usage

### ISSUE THREAD

**Issue by Juelianqvq** [vllm-project/vllm#5080]
What's the difference netween so many options. especially for marlin?
aqlm,awq,deepspeedfp,fp8,marlin,gptq_marlin_24,gptq_marlin,gptq,squeezellm,sparseml

**Comment by robertgshaw2-neuralmagic** [comment]
> What's the difference netween so many options. especially for marlin? aqlm,awq,deepspeedfp,fp8,marlin,gptq_marlin_24,gptq_marlin,gptq,squeezellm,sparseml

- `marlin` is for checkpoints that are serialized in marlin format
- `gptq_marlin` is for checkpoints that are serialized in gptq format, and we automatically convert to marlin format
- `gptq_marlin_24` is for checkpoints that are 2:4 sparse and quantized for 4 bits

We should clean this up though. Thanks for bringing this to my attention.

**Comment by josephrocca** [comment]
Hi @robertgshaw2-neuralmagic, how would one determine which option is best to use for a model that we've found on HuggingFace hub? e.g.

* https://huggingface.co/alpindale/Mistral-7B-Instruct-v0.2-Marlin
* https://huggingface.co/softmax/Llama-2-70b-chat-hf-marlin

For the latter, I've tried `gptq` and `marlin`, and they both seem to work. IIUC, `gptq` gets automatically converted to `marlin` if appropriate? Mainly I'm wondering when one should use `gptq_marlin_24`, and also whether there are any cases in which one should not use `gptq_marlin` - it seems like it's always better to use marlin if possible, and if vLLM can autoconvert it, then it seems like an easy choice?

Also, since I see you're on the nm-vllm team, can I also ask: Is there currently any performance benefit to using nm-vllm over vllm, or has the performance-relevant stuff been upstreamed to vllm?

**Comment by robertgshaw2-neuralmagic** [comment]
> Hi @robertgshaw2-neuralmagic, can I ask: how would one determine which option is best to use for a model that we've found on HuggingFace hub? e.g.
> 
> * https://huggingface.co/alpindale/Mistral-7B-Instruct-v0.2-Marlin
> * https://huggingface.co/softmax/Llama-2-70b-chat-hf-marlin
> 
> For the latter, I've tried `gptq` and `marlin`, and they both seem to work. IIUC, `gptq` flag automatically enabled `marlin` kernels if appropriate based on `config.json`? Mainly I'm wondering when one should use `gptq_marlin_24`, and also whether there are any cases in which one should not use `gptq_marlin` - it seems like it's always better to use marlin if possible, and if vLLM can autoconvert it, then it seems like an easy choice?
> 
> Also, since I see you're on the nm-vllm team, can I also ask: Is there currently any performance benefit to using nm-vllm over vllm, or has the performance-relevant stuff been upstreamed to vllm?

You do not have to pass a `--quantization` argument. We automatically detect from the HF Config the format of the model and just do the right thing.

For `gptq_marlin_24`, the model needs to be both 2:4 sparse and quantized. We will have some docs coming out soon on this.

For `nm-vllm` - we upstream all of the performance code to open-source. `nm-vllm` is our stable fork for customers

**Comment by josephrocca** [comment]
Thank you! :pray:

**Comment by robertgshaw2-neuralmagic** [comment]
@josephrocca added some more color

**Comment by josephrocca** [comment]
@robertgshaw2-neuralmagic I wonder if it's possible to add automatic conversion in vLLM so all the existing GPTQ quantizations "just work" with vLLM? 

That would allow options to be simplified somewhat I guess? I.e. just add `--quantization marlin` and it'll convert it if it's an old GPTQ.

I'm not sure if this is actually practical to do on-the-fly. I'm going by this tweet from TGI dev, which I may be misunderstanding:

>More Marlin features coming to the next @.huggingface TGI release: support for using **existing GPTQ-quantized models** with the fast Marlin matrix multiplication kernel.

> This feature is made possible by @.neuralmagic's Marlin kernel with GPTQ repacking support.

> If you want to try this with the development branch, just load your GPTQ model with TGI with '--quantize=marlin' in place of '--quantize=gptq'.

https://x.com/danieldekok/status/1804224598721830954

**Comment by robertgshaw2-neuralmagic** [comment]
> @robertgshaw2-neuralmagic I wonder if it's possible to add automatic conversion in vLLM so all the existing GPTQ quantizations "just work" with vLLM?
> 
> That would allow options to be simplified somewhat I guess? I.e. just add `--quantization marlin` and it'll convert it if it's an old GPTQ.
> 
> I'm not sure if this is actually practical to do on-the-fly. I'm going by this tweet from TGI dev, which I may be misunderstanding:
> 
> > More Marlin features coming to the next @.huggingface TGI release: support for using **existing GPTQ-quantized models** with the fast Marlin matrix multiplication kernel.
> 
> > This feature is made possible by @.neuralmagic's Marlin kernel with GPTQ repacking support.
> 
> > If you want to try this with the development branch, just load your GPTQ model with TGI with '--quantize=marlin' in place of '--quantize=gptq'.
> 
> https://x.com/danieldekok/status/1804224598721830954

This is how it currently works in vLLM … TGI took the kernels and code we use

**Comment by josephrocca** [comment]
Oh, facepalm, apologies. I somehow completely forgot about the `--quantization gptq_marlin` option you mentioned above, which does the conversion on-the-fly.

(Painful to add useless noise to any maintainer/developer's day, but even more so for someone like yourself who is doing such important work. Really sorry about this!)

**Comment by robertgshaw2-neuralmagic** [comment]
You’re all good - raising issue and asking questions is great feedback for us since it tells us where things could be made clearer

also - note that the automatic conversion is default behavior. If you’re on an ampere gpu and up, then we will use marlin by default

so I wouldn’t even touch the —quantization args. Just pass an autogptq compatible checkpoint and you’re good to go
