### ISSUE TITLE
curl http://localhost:8000/generate {"detail":"Not Found"}[Usage] generate relu can not ues

### ISSUE THREAD

**Issue by fishingcatgo** [vllm-project/vllm#5082]
run with python -m vllm.entrypoints.openai.api_server --model vicuna-7b-v1.5  --trust-remote-code

curl http://localhost:8000/generate -d '{"prompt": "Below is an instruction that describes a 
task. Write a response that appropriately completes the request.\n\n### Instruction:write a bubble sort using python\n\n### Response:","max_tokens":256}'

INFO:     127.0.0.1:55766 - "POST /generate HTTP/1.1" 404 Not Found
INFO 05-28 15:37:03 metrics.py:334] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO:     127.0.0.1:45622 - "GET /generate HTTP/1.1" 404 Not Found

python cli.py 
Prompt: 'San Francisco is a'

Traceback (most recent call last):
  File "/root/autodl-tmp/chat-main/vllm_cli.py", line 79, in <module>
    output = get_response(response)
  File "/root/autodl-tmp/chat-main/vllm_cli.py", line 46, in get_response
    output = data["text"]
KeyError: 'text'

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by DarkLight1337** [comment]
You can use the official [OpenAI Python client](https://github.com/openai/openai-python) to access vLLM's OpenAI-compatible server. The latest stable release supports Models API, Chat Completions API and Completions API.

**Comment by GanZhengha** [comment]
I have the same problem. It is strange, because i can run it a few days ago. Have you solved it?

**Comment by DarkLight1337** [comment]
`ttp://localhost:8000/generate` is only valid for the example server, not the OpenAI-compatible server. In the original post by @fishingcatgo,
`python -m vllm.entrypoints.openai.api_server --model vicuna-7b-v1.5 --trust-remote-code` runs the OpenAI-compatiable server instead of the example server.

**Comment by GanZhengha** [comment]
`python -m vllm.entrypoints.api_server \
--model /workspace/opt-125m \
--port 9760 \
--gpu-memory-utilization 0.5`
this is the code i run the server. I got 404 when i run both `curl http://localhost:9760/v1/models` and `client.completions.create`

**Comment by DarkLight1337** [comment]
> `python -m vllm.entrypoints.api_server \ --model /workspace/opt-125m \ --port 9760 \ --gpu-memory-utilization 0.5` this is the code i run the server. I got 404 when i run both `curl http://localhost:9760/v1/models` and `client.completions.create`

Can you try setting `--host 0.0.0.0` instead of the default `--host localhost`?

**Comment by GanZhengha** [comment]
I have tried, it seems not work.

> > `python -m vllm.entrypoints.api_server \ --model /workspace/opt-125m \ --port 9760 \ --gpu-memory-utilization 0.5` this is the code i run the server. I got 404 when i run both `curl http://localhost:9760/v1/models` and `client.completions.create`
> 
> Can you try setting `--host 0.0.0.0` instead of the default `--host localhost`?

**Comment by DarkLight1337** [comment]
> I have tried, it seems not work.

Can you show the log of both the server and client?

**Comment by GanZhengha** [comment]
server:
`INFO 06-04 02:31:05 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='/workspace/opt-125m', speculative_config=None, tokenizer='/workspace/opt-125m', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/workspace/opt-125m)
INFO 06-04 02:31:06 model_runner.py:146] Loading model weights took 0.2389 GB
INFO 06-04 02:31:07 gpu_executor.py:83] # GPU blocks: 34192, # CPU blocks: 7281
INFO 06-04 02:31:10 model_runner.py:854] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-04 02:31:10 model_runner.py:858] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-04 02:31:13 model_runner.py:924] Graph capturing finished in 3 secs.
INFO:     Started server process [486571]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9760 (Press CTRL+C to quit)
INFO:     127.0.0.1:33664 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:35442 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56994 - "POST /v1/completions HTTP/1.1" 404 Not Found
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.`
client:
`Traceback (most recent call last):
  File "/workspace/api_inference.py", line 11, in <module>
    completion = client.completions.create(model="/workspace/opt-125m",
  File "/opt/conda/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/openai/resources/completions.py", line 516, in create
    return self._post(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1233, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 922, in request
    return self._request(
  File "/opt/conda/lib/python3.10/site-packages/openai/_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}`
code in api_inference:
'from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://0.0.0.0:9760/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
for i in range(10):
    completion = client.completions.create(model="/workspace/opt-125m",
                                        prompt=f"San Francisco is a {i}")
    print("Completion result:", completion)'
I could use this a few days ago, it's also ok to run vllm offline. So, I wonder whether it's a problem of network or openai's version. I have tried to change openai's version several times, but still can't work. Or, does the close of  ECC influence? The ECC on our remote server has been disabled due to other experiments.

**Comment by DarkLight1337** [comment]
Can you try using `curl` to send requests directly? (By the way, when you were hosting on `localhost`, did you also access the server via `localhost`?)

**Comment by GanZhengha** [comment]
I have tried `curl http://localhost:9760/v1/models` ，receive `{"detail":"Not Found"}` and `INFO:     127.0.0.1:54932 - "GET /v1/models HTTP/1.1" 404 Not Found` in server's log.

**Comment by DarkLight1337** [comment]
For detailed debugging, I recommend that you launch the OpenAI-compatible server in a debugger and add a breakpoint in `fastapi.FastAPI.__call__` (which handles the incoming request) to go through the code and see where it breaks.

An example debugger config in VSCode would be:
```

        {
            "name": "Python Debugger: Zephyr (OpenAI server)",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/vllm/entrypoints/openai/api_server.py",
            "console": "integratedTerminal",
            "args": [
                "--port",
                "9760",
                "--model",
                "/workspace/opt-125m",
            ],
            "justMyCode": false
        },
```

**Comment by youkaichao** [comment]
@GanZhengha it seems you are using `vllm.entrypoints.api_server`, which is deprecated and does not support `http://localhost:8000/v1/models`.

You should use `vllm.entrypoints.openai.api_server` .  It does not support `/generate` though. Typical usage is through openai client.

Sorry for the confusion, but we have two api servers with different urls to respond.

**Comment by DarkLight1337** [comment]
You passed `--port 8000`, so the server should be on port 8000, not 60616

**Comment by cqray1990** [comment]
> You passed `--port 8000`, so the server should be on port 8000, not 60616
NO its port auto changed 

parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default=None)
    parser.add_argument("--port", type=int, default=8001)
    parser.add_argument("--model-url",
                        type=str,
                        default="http://localhost:8000/generate")
    args = parser.parse_args()

    demo = build_demo()
    demo.queue().launch(server_name=args.host,
                        server_port=args.port,
                        share=True)

**Comment by DarkLight1337** [comment]
Do you have another process that is using port 8000? In any case, the port should be shown when the server is running. Make sure your `model-url` argument is consistent with the actual port that is used.

**Comment by cqray1990** [comment]
> Do you have another process that is using port 8000? That may be why the port changed. In any case, the port should be shown when the server is running. Make sure your `--model-url` argument is consistent with the actual port that is used.

@DarkLight1337 
is "http://localhost:8000/generate" an right route to access?

**Comment by DarkLight1337** [comment]
The URL should have the same port number as the one in the message like `INFO: Uvicorn running on http://0.0.0.0:8898/ (Press CTRL+C to quit)`. If you can't get a consistent port number, make sure the port isn't already being used by another process.

**Comment by cqray1990** [comment]
> The URL should have the same port number as the one in the message like `INFO: Uvicorn running on http://0.0.0.0:8898/ (Press CTRL+C to quit)`. If you can't get a consistent port number, make sure the port isn't already being used by another process.
you doubt 8000 is used so i change to 8898 , and  ''http;localhost:8898/generate"

**Comment by DarkLight1337** [comment]
Sorry I got a bit confused - you should set `--model-url` to the port of `vllm serve`. Then, the `--port` here should refer to the gradio server, not `vllm serve`

**Comment by cqray1990** [comment]
> Sorry I got a bit confused - you should set `--model-url` to the port of `vllm serve`. Then, the `--port` here should refer to the gradio server, not `vllm serve`

@DarkLight1337  t change discription above

**Comment by DarkLight1337** [comment]
What are the command-line arguments you passed to `[examples/online_serving/gradio_webserver.py](https://github.com/vllm-project/vllm/blob/main/examples/online_serving/gradio_webserver.py)`?

**Comment by cqray1990** [comment]
> What are the command-line arguments you passed to `examples/online_serving/gradio_webserver.py`? The `port` you set here should be a different one from `vllm serve`.

gradio_webserver.py called vllm serve 
 response = requests.post(args.model_url,
                             headers=headers,
                             json=pload,
                             stream=True)


def http_bot(prompt):
    headers = {"User-Agent": "vLLM Client"}
    pload = {
        "prompt": prompt,
        "stream": True,
        "max_tokens": 128,
    }
    response = requests.post(args.model_url,
                             headers=headers,
                             json=pload,
                             stream=True)

    for chunk in response.iter_lines(chunk_size=8192,
                                     decode_unicode=False,
                                     delimiter=b"\0"):
        if chunk:
            data = json.loads(chunk.decode("utf-8"))

            output = data["text"][0]
            yield output

**Comment by DarkLight1337** [comment]
`examples/online_serving/gradio_webserver.py` starts a gradio server that communicates with the server from `vllm serve`. These two servers are on different ports.

**Comment by cqray1990** [comment]
> `examples/online_serving/gradio_webserver.py` starts a gradio server that communicates with the server from `vllm serve`. These two servers are on different ports.

how to use?

           response = requests.post(args.model_url,
                                         headers=headers,
                                         json=pload,
                                         stream=True)

**Comment by DarkLight1337** [comment]
`examples/online_serving/gradio_webserver.py` has the following command line arguments:
- `--port` is the port of the gradio server
- `--model-url` is the endpoint of the vLLM server. You should set the URL based on which endpoint you want to use.

**Comment by cqray1990** [comment]
> `examples/online_serving/gradio_webserver.py` has the following command line arguments:
> 
>     * `--port` is the port of the gradio server
> 
>     * `--model-url` is the endpoint of the vLLM server. You should set the URL based on which endpoint you want to use.

i want to call vllm serve by a gradio ui,

**Comment by DarkLight1337** [comment]
The port of the gradio server can be set to anything as long as it doesn't conflict with an existing port. `--model-url` can be set to `http://localhost:<vllm_port>/v1/completions` if you want to use OpenAI Completions API.

**Comment by cqray1990** [comment]
> `completions`

@DarkLight1337 
model-url  = "http://localhost:8000/v1/completions" but
INFO:     Started server process [1094361]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:59684 - "POST /v1/completions HTTP/1.1" 400 Bad Request

**Comment by DarkLight1337** [comment]
This file is originally designed for use with the legacy `vllm/entrypoints/api_server.py` rather than `vllm serve`.

**Comment by cqray1990** [comment]
> This file is designed for use with the legacy `vllm/entrypoints/api_server.py` rather than `vllm serve`.

i see thee lastest code is use vllm serve to start server

https://docs.vllm.ai/en/latest/getting_started/quickstart.html

**Comment by DarkLight1337** [comment]
Yes, so you have to edit `examples/online_serving/gradio_webserver.py` to work with `vllm serve`.

**Comment by DarkLight1337** [comment]
The port can be read from this message, e.g.

```
INFO: Uvicorn running on http://0.0.0.0:8898/ (Press CTRL+C to quit)
```

means the vLLM port is 8898

**Comment by cqray1990** [comment]
> The port can be read from this message, e.g.
> 
> ```
> INFO: Uvicorn running on http://0.0.0.0:8898/ (Press CTRL+C to quit)
> ```
> 
> means the vLLM port is 8898

ok now ,

fist start vllm opencao server

CUDA_VISIBLE_DEVICES=1,2 python -m vllm.entrypoints.openai.api_server \
  --model /eepSeek-R1-Distill-Qwen-7B \
  --served-model-name DeepSeek-R1-Distill-Qwen-7B \
  --max-model-len=1024
  --port 8898


seond:
run examples/online_serving/gradio_webserver.py   mode=url="http://localhost:8898/v1/completions"
but the gradio_webserver.py raise 

aise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8898): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d9c1e1c90>: Failed to establish a new connection: [Errno 111] Connection refused'))




and vllm openai,api_server log is:

INFO 02-12 19:04:33 launcher.py:29] Route: /v1/completions, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /v1/embeddings, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /pooling, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /score, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /v1/score, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /rerank, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /v1/rerank, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /v2/rerank, Methods: POST
INFO 02-12 19:04:33 launcher.py:29] Route: /invocations, Methods: POST
INFO:     Started server process [1182890]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

his port is always is 8000

**Comment by cqray1990** [comment]
> If it says the port is `8000` for vllm then I guess you should use `8000` in `--model-url` and set a different one for `--port` in the gradio server. Not sure why that's the case though.
can you   test the examples/online_serving/gradio_webserver.py and tell me the settings?

i also try the parameters as follows:
    parser.add_argument("--port", type=int, default=8001)
    parser.add_argument("--model-url",
                        type=str,
                        default="http://localhost:8000/v1/completions")  #"http://localhost:8000/generate"
    args = parser.parse_args()

    demo = build_demo()
    demo.queue().launch(server_name=args.host,
                        server_port=args.port,
                        share=True)

**Comment by cqray1990** [comment]
> I suggest you read the code in the file to understand how it actually works, then modify it to suit your needs.
the way i call the server of vllm by gradio_webserver.py is not right?
gradio_webserver is regarded as an client to call the server, and interact with ui

**Comment by DarkLight1337** [comment]
It is another server that serves the UI. You should edit the file so it can send requests to the correct vLLM endpoint.
