### ISSUE TITLE
[Usage]: vllm server mode, gpu util

### ISSUE THREAD

**Issue by UbeCc** [vllm-project/vllm#6131]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I'm using vllm `0.4.0.post1`, and I want to use [Llama3-8b-instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) to infer a lot of data. As the pieces of data have dependencies, I cannot use vllm directly, so I start the server mode.

However, I note that my GPU-UTIL is constantly below 50% (8xA100-40G). I think it is due to small prompt queue passed to vllm server, so I use multiprocessing.Queue and concurrent.futures import ThreadPoolExecutor to infer parallelly and set **Count(Progress) * Count(Thread) = 1000**. 

And the  GPU-UTIL is still below 50%. I want to fully utilize my gpu, but I don't know whether it is a feature of vllm. Thanks for your time!

**Comment by hmellor** [comment]
Are you running one instance of vLLM with `--tensor-parallel-size 8`? Using such a large tensor parallel size on such a small model will lead to poor performance. I would not recommend it.

I would recommend using something like https://github.com/lm-sys/FastChat and start 1 controller and 8 vLLM workers.

Since you are using a server you should be using `async` to make concurrent requests, not multiprocessing.

**Comment by UbeCc** [comment]
> Are you running one instance of vLLM with `--tensor-parallel-size 8`? Using such a large tensor parallel size on such a small model will lead to poor performance. I would not recommend it.
> 
> I would recommend using something like https://github.com/lm-sys/FastChat and start 1 controller and 8 vLLM workers.
> 
> Since you are using a server you should be using `async` to make concurrent requests, not multiprocessing.

Yes I did use `--tensor-parallel-size 8`, and I tried to start 8 servers. It works well, thanks!
