### ISSUE TITLE
How much does 'GPU memory utilization' parameter affect GPU performance?

### ISSUE THREAD

**Issue by jaes77** [vllm-project/vllm#659]
That parameter is 0.9 as a default. and That makes really high VRAM occupancy when 350m model is loaded like below.
![image](https://github.com/vllm-project/vllm/assets/103483570/9e380c2b-fc34-4877-b4e5-02a1884aeaaa)

When the parameter's decreased, will the overall performance be dropped?
In addition, does it affect SM warp occupancy?
Please explain the relationship between gpu memory utilization parameter and overall performance.

**Comment by LiuXiaoxuanPKU** [comment]
vllm preallocates memory during initialization. 73G here includes the memory for kv cache (also model weights). if you use a smaller parameter, it means smaller total memory usage, therefore a smaller kv cache (because the model size does not change). 

On the online setting, the size of kv cache will affect vllm's the max service rate (because we observe most models are capacity/bandwidth bound). It generally will not affect the performance when the request rate < max service rate. Warp occupancy is more about compute utilization. It depends more on your request rate.

Feel free to reply here if you have more questions.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
