### ISSUE TITLE
[Performance]: Llava runs with small batch size and # of GPU blocks

### ISSUE THREAD

**Issue by jaywonchung** [vllm-project/vllm#6623]
### Misc discussion on performance

I was running `llava-hf/llava-1.5-7b-hf` vs. `meta-llama/Meta-Llama-3-8B-Instruct` on vLLM 0.5.2 and noticed that Llava 7B runs with a significantly smaller batch size overall -- Llama 3 8B would hit the maximum batch size 256, whereas Llava 7B would remain in the 70~80 range. I do notice that Llava 7B begins with much less GPU blocks allocated (# GPU blocks: 3631, # CPU blocks: 512) compared to LLama 3 8B (# GPU blocks: 13078, # CPU blocks: 2048), which probably explains the batch size.

I wanted to understand whether this difference (existence and magnitude) is expected and the causes. I can think of some reasons that contribute to this:
- Parameters of the vision tower and multimodal projector
  - Less than half a billion parameters
- Activations of the vision tower and multimodal projector
  - They can't be *that* big, can they? I believe they can also be deallocated after generating the image embeddings.
- Image tokens inserted into the prompt
  - I attempted to read the source code and it seems like it's 576 image tokens? If so I suppose that's a fair amount. But does this get reflected in the number of GPU blocks?

Thanks.

### Your current environment (if you think it is necessary)

PyTorch version: 2.3.1+cu121
CUDA used to build PyTorch: 12.1

Single NVIDIA A40 GPU with 46068 MiB VRAM.

**Comment by ywang96** [comment]
Hey @jaywonchung! Thank you for testing out vision language models on vLLM and raising this issue!

First of all, the way GPU profiling works on vLLM is that: given a configuration (model, max-model-len, max-num-seqs, gpu-memory-util %, etc), we run "fake" inference and determine how much free GPU memory there is after running it, then use that free memory to allocate GPU blocks.

In the context of vision language model, we need to process the pixel values of image through the CLIPVisionModel and Multimodal projector in addition to text/prompt, and all this happens on GPU (meaning not just the loaded `nn.module`, but also the result tensors). You can see during profiling we actually create dummy PIL images here https://github.com/vllm-project/vllm/blob/396d92d5e064d131422886482cb1b75e5b6538d9/vllm/model_executor/models/clip.py#L59

One other caveat is that during profiling, we assume **each request will come with an image**, and this means we need to override `--max-num-seqs` for this assumption. While this assumption might not always be the case during the actual usage, we need to profile this way so that it the engine wouldn't never run into OOM issue. You can check this logic here
https://github.com/vllm-project/vllm/blob/396d92d5e064d131422886482cb1b75e5b6538d9/vllm/worker/model_runner.py#L715-L720

Finally, this does not apply to your case since you're using a single GPU, but currently the vision model and multimodal projector is not tensor parallelized, meaning they will be instantiated on each GPU if you're using multiple GPUs. Enabling TP for them is on our roadmap that you can check here https://github.com/vllm-project/vllm/issues/4194#issue-2252314187

**Comment by jaywonchung** [comment]
Thank you so much for your kind response @ywang96!

So indeed, the vision tower and multimodal projector do take quite a bit of memory, especially when we assume that every request has an image and the two modules are forwarded with the largest possible batch size. Just checked with `llava-1.5-7b-hf` and confirmed that `max_num_seq` gets reduced from 256 to 7.

However, perhaps more influential is that Llava's cache block size is exactly 4x larger than Llama 3's. I just figured it out by logging the number out but I suppose it was also evident from the fact that Llama 3 has 4x the number of CPU blocks. I suppose if a token takes 4x the memory, Llava runnning slower is completely fair 😅
