### ISSUE TITLE
[Bug]: Qwen1.5( vllm>=0.4.2)  streaming generate token is abnormal.Using  engine.generate()

### ISSUE THREAD

**Issue by BWZhang-NLP** [vllm-project/vllm#6638]
### Your current environment

```text
A800*8 ，vllm==0.4.3
```

### 🐛 Describe the bug

```
results_generator = engine.generate(prompt_format, sampling_params, request_id)
pre_index=0
async for request_output in results_generator:
    text_outputs = [output.text for output in request_output.outputs][0][pre_index:]
    pre_index+=len(text_outputs)
    res+=text_outputs
    ret = {'code': 1, 'answer':text_outputs,"request_id":request_id}
    yield (json.dumps(ret)).encode("utf-8")
```
The `text ` field is error in the streaming result, but `token_ids ` field is normal.

![1721636495461](https://github.com/user-attachments/assets/4b683555-a778-44ac-8c8b-e3f4d30848ba)

**Comment by mpoemsl** [comment]
I know this is an old issue, but just wanted to note I encountered a similar issue. In my case, it was because of the `include_stop_str_in_output` logic [here](https://github.com/vllm-project/vllm/blob/96846bb3607370798540c7d325f8d06dbd67dcf4/vllm/v1/engine/detokenizer.py#L78). Using `stop_ids` instead of `stop` helped.
