### ISSUE TITLE
Does vllm support vicuna-13b-v1.5-16k ?

### ISSUE THREAD

**Issue by Extremys** [vllm-project/vllm#674]
The model seems to loop in its outputs
<img width="1250" alt="image" src="https://github.com/vllm-project/vllm/assets/7710663/5837077b-d5f2-4c60-b18b-2afb4f8c1082">

I'm using: 
vllm 0.1.2
transformers 4.31.0
launched through the FastChat (commit [b0462aa](https://github.com/lm-sys/FastChat/commit/b0462aa6f028af2065a1691e83a563eccc43ea20) )/vllm wrapper (worker)
Any idea on what's going on? Thanks.

**Comment by DiscordJim** [comment]
Having same issue with vLLM 0.1.3.

**Comment by LiuXiaoxuanPKU** [comment]
Currently, vllm does not support 16k because the model uses rope embedding as shown [here](https://huggingface.co/lmsys/vicuna-7b-v1.5-16k/blob/9a93d7d11fac7f3f9074510b80092b53bc1a5bec/config.json#L21). We are actively working on it as show in pr #555, vllm will support vicuna-13b-v1.5-16k after that pr.

**Comment by Zhuqln** [comment]
thanks a lot for your effort. i use the pr and works well.
i have another question  about long-context. when i use more than 2.5k-len context then i get an warning about `exceeds limit.`
it means vllm can not afford long-context ?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
