### ISSUE TITLE
ImportError: cannot import name 'activation_ops'

### ISSUE THREAD

**Issue by prashanthkolaneru** [vllm-project/vllm#705]
I cloned the repository

**Comment by NonaryR** [comment]
same here, I can reproduce even on v0.1.3 tag

**Comment by plumber-craic** [comment]
is there a workaround for this?

**Comment by prashanthkolaneru** [comment]
I tried but its not working. I can import vllm but when I tried to pasd the
model I am facing the same problem.

**Comment by photomz** [comment]
I had this issue but fixed by installing `pip install -e .` instead of `pip install -r requirements.txt`.

### Why

`activation_ops` is a CUDA function that's bound to Python during [setup.py](https://github.com/vllm-project/vllm/blob/d1744376ae9fdbfa6a2dc763e1c67309e138fa3d/setup.py#L108):

```py
# Activation kernels.
activation_extension = CUDAExtension(
    name="vllm.activation_ops",
    sources=["csrc/activation.cpp", "csrc/activation_kernels.cu"],
    extra_compile_args={"cxx": CXX_FLAGS, "nvcc": NVCC_FLAGS},
)
ext_modules.append(activation_extension)
```

When you only install `requirements.txt`, none of the CUDA bindings (aka FlashAttention) that make vllm so fast are compiled and connected to Python. Instead, `pip install -e .` runs `setup.py` to correctly install the package.

> Note: `setup.py` builds from source, which could take many minutes.

**Comment by timxx** [comment]
Just cd out of the vllm directory solved the problem for me.

**Comment by Alroy261** [comment]
> Just cd out of the vllm directory solved the problem for me.

This works for me! TY @timxx
