### ISSUE TITLE
Did vLLM support flashatten to save the memeory?

### ISSUE THREAD

**Issue by Zhuqln** [vllm-project/vllm#714]
when i use flash-atten to do the `fschat/long-eval` test . i see the flash-attn saves a lot of gpu-memory usage.

so im wondering if vLLm support this too?

**Comment by WoosukKwon** [comment]
Hi @Zhuqln thanks for the great question. Instead of the `flash-attn` library, we use `xformers`, which provides FlashAttention-like memory-efficient attention implementations. We prefer `xformers` since it supports a wider range of GPUs, data types, and attention algorithms than `flash-attn` and can be installed with pre-compiled CUDA binaries.
