### ISSUE TITLE
[Feature]: Adjust max_model_len based on viable KV space

### ISSUE THREAD

**Issue by mscheong01** [vllm-project/vllm#7195]
### 🚀 The feature, motivation and pitch

Currently, when loading a model onto a GPU that doesn't have sufficient memory for full max_len sized KV cache, this error pops up:
```
ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (22032). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```
Which originates from this code:
https://github.com/vllm-project/vllm/blob/9118217f58c39040aa935b7c85250c7364ffa72d/vllm/worker/worker.py#L214-L216

Although there are some workarounds can be found [here](https://github.com/vllm-project/vllm/issues/2418), wouldn't it be better to adjust the `self.model_config.max_model_len`size to the maximum affordable size?
We could pop a warning to notify that the full context length cannot be used.

If this idea is OK, I'd love to attempt a fix. Thanks for reading 🙇‍♂️

**Comment by ganisback** [comment]
I love this solution. vllm can adjust max_model_len automically based on GPU resources

**Comment by youkaichao** [comment]
thanks for your interest. I discussed the possibility with many contributors, and we find it is not easy to simply update the max_model_len according to the available kv cache size.

many components in vLLM already remember the max_model_len value, and take decision with that value. if we directly update the max_model_len, some component can be in wrong state, which will shutdown the inference engine with some long requests.

therefore, it is better to fail fast, rather than to fail on a specific request.

**Comment by mscheong01** [comment]
Thanks for your reply 😞 
Can we not check and apply the available model len size when initializing the LLM engine before other components are created?
https://github.com/vllm-project/vllm/blob/746709642c81aa22926765aef67e086a15aef076/vllm/engine/llm_engine.py#L157
Otherwise, I guess I'll have to hope that some future change in the codebase enables this. Thanks for your consideration 🙇‍♂️
