### ISSUE TITLE
[Usage]: Increase the maximum number of running reqs, which now seems to default to 100

### ISSUE THREAD

**Issue by Vodkazy** [vllm-project/vllm#7241]
### Your current environment

How do I increase the maximum number of concurrent reqs, which now seems to default to 100

### How would you like to use vllm

The current command is as following:
```
python -m vllm.entrypoints.openai api_server ——enable-prefix-caching ——disable-log-request
```

**Comment by hieu-blackbox** [comment]
Is there any argument to increase this number?

**Comment by adamo1139** [comment]
I had the same issue - cap at 100 concurrent requests, but only on some scripts and not others. Turns out it was because of how I was making requests using aiohttp. After I set aiohttp TCPConnector `limit` and `limit_per_host` to higher values, it started working as expected. Please check your script to make sure you're not using aiohttp with defaults.
