### ISSUE TITLE
[Bug]: Miscalculation for ITL

### ISSUE THREAD

**Issue by AslanEZ** [vllm-project/vllm#7242]
### Your current environment

This bug is irrelevant to environment.

### 🐛 Describe the bug

Thanks for open source such a excellent project!
I found it possibly misses an "else" in the async_request_openai_completions function of 'benchmarks
/backend_request_func.py'.

```
                           if data["choices"][0]["text"]:
                                timestamp = time.perf_counter()
                                # First token
                                if ttft == 0.0:
                                    ttft = time.perf_counter() - st
                                    output.ttft = ttft

                                # Decoding phase
                                # Missing 'else:' here !!!!
                                output.itl.append(timestamp -
                                                  most_recent_timestamp)

                                most_recent_timestamp = timestamp
                                generated_text += data["choices"][0]["text"]
```
It cause the function incorrectly append TTFT into ITL list. Curiously, I saw others request function in the file have this conditional statement.

By the way, I found most of articles said TPOT is same as ITL. Could you tell me what's the difference between TPOT and ITL in the benchmark of vllm?
Thanks a lot.

**Comment by youkaichao** [comment]
cc @KuntaiDu

**Comment by ywang96** [comment]
@AslanEZ I think you're right here that we're missing a `else` gate here - do you mind opening a PR to fix this?

In this benchmark we're using TPOT and ITL a bit differently - you can find the exact calculation in the code, but here is an example for the sake of comparison:

For a benchmark of 1000 requests:

`TPOT` is a request-level metric, meaning for each request, we look at its `(end-to-end latency - TTFT)/ (number of output tokens - 1)`. Here, the number of output tokens is calculated by detokenizing the result output with the model's tokenizer (so it could be potentially inaccurate/off by 1 or 2, but we'd argue it's fair as long as we use the same calculation for all backends). Therefore we will have 1000 TPOT numbers after running the benchmark

`ITL` is a global metric, we simply record the latency between every two server-side events (SSE) as long as it's not the first token. Here number of output tokens is then derived by simply looking at how many SSEs there are. This means after running the benchmark, we will have `sum of number of all output tokens - 1000` ITL numbers.

The interesting difference here is that, for some backends, they `bundle` multiple token generations into one SSE, therefore number of SSEs (and thus ITL itself) can be actually misleading. We still decide to keep them in the benchmark, since we know vLLM strictly follows one SSE per token protocol.

Hope that answer your question!

P.S. @youkaichao I probably have the most context since I pretty much worked on this entire serving benchmark :P, so feel free to tag me in the future.

**Comment by AslanEZ** [comment]
@ywang96 Yeah, I'd like to, but I think you had fixed it now.
Anyway, thanks for your answer and help!

**Comment by initzhang** [comment]
Hi @ywang96 , thanks for the explanation about ITL and TPOT! 

I would like to ask whether it is possible to reconstruct/recompute raw TPOT from the saved benchmark json result? 

It seems that the `benchmark_serving.py` script would not save the e2e latency as well as the calculated tpots for each request in the json file (the [benchmark_result](https://github.com/vllm-project/vllm/blob/f842a7aff143a4a1ddc59e1fb57109cb377f5475/benchmarks/benchmark_serving.py#L641) object has no [related fields](https://github.com/vllm-project/vllm/blob/f842a7aff143a4a1ddc59e1fb57109cb377f5475/benchmarks/benchmark_serving.py#L449)).

**Comment by ywang96** [comment]
> Hi @ywang96 , thanks for the explanation about ITL and TPOT!
> 
> I would like to ask whether it is possible to reconstruct/recompute raw TPOT from the saved benchmark json result?
> 
> It seems that the `benchmark_serving.py` script would not save the e2e latency as well as the calculated tpots for each request in the json file (the [benchmark_result](https://github.com/vllm-project/vllm/blob/f842a7aff143a4a1ddc59e1fb57109cb377f5475/benchmarks/benchmark_serving.py#L641) object has no [related fields](https://github.com/vllm-project/vllm/blob/f842a7aff143a4a1ddc59e1fb57109cb377f5475/benchmarks/benchmark_serving.py#L449)).

Hmm, I actually did add e2e latency in this benchmark output object, but it's just that I didn't save in the benchmark result
https://github.com/vllm-project/vllm/blob/f842a7aff143a4a1ddc59e1fb57109cb377f5475/benchmarks/backend_request_func.py#L31-L39
It shouldn't be hard to add it into the result since it's already available.

If you really want to do it now, for a particular request, you can average `sum(itl)` over the number of tokens of `generated_text` to calculate the raw TPOT.

**Comment by cermeng** [comment]
> We still decide to keep them in the benchmark, since we know vLLM strictly follows one SSE per token protocol.

@ywang96 It seems not true for speculative decoding. 

ITL is inaccurate when vllm enables the speculative decoding feature that generates multiple tokens in one step. However, TPOT is accurate as the output length also increases, and TPOT is calculated using the equation (e2e latency - ttft) / (output_len - 1).

What if we consider adding a new metric in benchmark such as TPGS (tokens per generation step) or TPSP (tokens per SSE protocol) to better illustrate this type of scenario. Perhaps we should also consider adding additional metrics, such as a new ITL calculated based on TPSGS or TPSP.
