### ISSUE TITLE
[Feature]: support voice llm like cosyvoice

### ISSUE THREAD

**Issue by balcklive** [vllm-project/vllm#7335]
### 🚀 The feature, motivation and pitch

As we can see that vllm already support many vision language models. Do we have a plan to support voice models like cosyVoice?

**Comment by ywang96** [comment]
I took a like at the architecture of CosyVoice and it looks a bit more complicated than what we can support today (mostly because of the flow matching).

However, we should be able to support audio-LLM with simple encoder + LM architecture (such as Qwen-audio) pretty easily given our current infrastructure for multi-modality. If you're interested, please feel free to open a PR!
