### ISSUE TITLE
[Bug]: vllm online mode gives variance logprobs even if temperature is 0 with same prompt

### ISSUE THREAD

**Issue by tonyaw** [vllm-project/vllm#7779]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

For vllm online mode, I observed the logprob is slightly different with same prompt, same openai client parameter and temperature is 0 for different outputs. Please see two examples at the bottom of this message.
It may cause unexpected output sometimes.
What I want is a deterministic and consistent output for a same prompt in multiple runs.
The openai client parameter in use is:
```
024-08-22 07:45:26: openai_client_call: model_kwargs={'model': 'hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4', 'stream': False, 'max_tokens': 10240, 'temperature': 0, 'n': 1, 'seed': 42, 'extra_body': {'top_k': 1}, 'logprobs': True, 'top_logprobs': 5}
```

Interesting thing here is if I use offline mode, the logprob is always same regardless how many times run.
What's the difference between offline mode and online mode? Any suggestion for this issue?
Thanks in advance!

First token generated twice. Although the order is same, but logprob isn't 100% same.
```
2024-08-22 07:44:53: LOGPROBS in json=
2024-08-22 07:44:53: [
    {
        "token": "Based",
        "logprob": 0.29491642842156046,
        "top_logprobs": [
            {
                "token": "Based",
                "logprob": "-1.221063256263733(0.29491642842156046)"
            },
            {
                "token": "I",
                "logprob": "-1.267938256263733(0.28141122190367795)"
            },
            {
                "token": "Let",
                "logprob": "-1.767938256263733(0.17068453407177606)"
            },
            {
                "token": "After",
                "logprob": "-2.0179381370544434(0.13292926463967933)"
            },
            {
                "token": "```",
                "logprob": "-3.2366881370544434(0.03929381557261831)"
            }
        ]
    },
```

```
2024-08-22 07:45:33: LOGPROBS in json=
2024-08-22 07:45:33: [
    {
        "token": "Based",
        "logprob": 0.29833433664184544,
        "top_logprobs": [
            {
                "token": "Based",
                "logprob": "-1.2095404863357544(0.29833433664184544)"
            },
            {
                "token": "I",
                "logprob": "-1.2720404863357544(0.2802591729271426)"
            },
            {
                "token": "Let",
                "logprob": "-1.7720404863357544(0.1699857810460168)"
            },
            {
                "token": "After",
                "logprob": "-2.022040367126465(0.13238507517117207)"
            },
            {
                "token": "```",
                "logprob": "-3.256415367126465(0.038526253263656336)"
            }
        ]
    },
```

**Comment by robertgshaw2-neuralmagic** [comment]
We use `marlin` kernel for AutoAWQ models. `marlin` is faster than the `awq` kernel, but it has some slight nondeterminism due to some internal locking mechanism that can change the order of operations (which impacts numerics)

We have extensively tested the accuracy of marlin end-to-end and are confident it produces the same overall scores. That being said, if you want strict determinism, run with `--quantization awq` to disable marlin

**Comment by tonyaw** [comment]
@robertgshaw2-neuralmagic , Thanks for your response!
Based on my experiment, looks like max_num_seqs 1 can always get deterministic result(Run 500 times). 
(I don't set  --quantization awq).
Could you please help to explain the reason here?

**Comment by tonyaw** [comment]
@robertgshaw2-neuralmagic , also I saw deterministic result with vllm offline mode with marlin.
Could you please also help to explain the reason?

**Comment by robertgshaw2-neuralmagic** [comment]
oh - you're running in batch mode, this is not due to `marlin`. There is no way to guarantee exactly equal outputs due to the way Nvidia GPUs work and the limitations of numerics.

Specifically, you are running with FP16 activations, which has limited precision. Unfortunately, matrix multiplication on Nvidia GPUs is NOT associative, meaning the order of operations can impact accuracy scores.

So, you will have slightly different values running at batch size N vs batch size M due to these numerics or even with the same batch size but different values inside your batch. This is the root cause of the differences. In server mode, the batches are likely slightly different, which leads to the slightly different logprobs

**Comment by tonyaw** [comment]
Thanks for your detailed info. Could you please help to explain more?
1. When(which scenario) will marlin impact determinism?
2. It seems impossible to get deterministic result with marlin. Then why I can get deterministic result with marlin when I set max_num_seqs to 1 for 500 rounds?
3. I'm confused by "even with the same batch size but different values inside your batch". By default, max_num_seqs is 256, which means batch_size is always same and shall be 256, right? If Yes, could you please explain more about this root cause?
Thanks in advance!

**Comment by robertgshaw2-neuralmagic** [comment]
> Thanks for your detailed info. Could you please help to explain more?
> 
> 1. When(which scenario) will marlin impact determinism?
> 2. It seems impossible to get deterministic result with marlin. Then why I can get deterministic result with marlin when I set max_num_seqs to 1 for 500 rounds?
> 3. I'm confused by "even with the same batch size but different values inside your batch". By default, max_num_seqs is 256, which means batch_size is always same and shall be 256, right? If Yes, could you please explain more about this root cause?
>    Thanks in advance!

I apologize for not being clear. 

When you originally posted the issue, I assumed it was a `marlin` nondeterminism issue. In recent versions of vllm, we have made some steps to eliminate this as much as possible (specifically the recent versions of vllm use an fp32 global reduce rather than an fp16 global reduce). We should not be seeing much nondeterminism anymore

What you are seeing (where batching causes slight numerical differences between runs) is true of all inference kernels and is unrelated to marlin. You will see similar results for `awq`, `fp16`, `fp8`, etc etc. It is due to the fact that fp16 matrix multiplication is not associative! The order of operations matters. So even slight differences in the batch size of the makeup of the batch will slightly impact the results. This is fundamental to GPU architecture.

Does this make sense? Root cause is that numerics on GPUs will cause slight differences in logprobs.

**Comment by tonyaw** [comment]
Thanks for your further explanation!
So, even if I change the model format from AWQ to the native one - "meta-llama/Meta-Llama-3-70B-Instruct"(fp16), the nondeterminism issue will still be there, Right?

The only solution is to give up the batching, and always use max_num_seqs=1/offline_mode to do the inference. Right? :-)

**Comment by tonyaw** [comment]
> Thanks for your further explanation!
> 
>     1. So, even if I change the model format from AWQ to the native one - "meta-llama/Meta-Llama-3-70B-Instruct"(fp16), the nondeterminism issue will still be there, Right?
> 
>     2. When I set max_num_seqs, does it mean I disable batching(batch_size=1)?
> 
>     3. The only solution is to always use max_num_seqs=1/offline_mode to do the inference. Right?
> 
>     4. If I set max_num_seqs=1, doesn't it mean vllm won't need multiple matrix multiplication, so that "fp16 matrix multiplication is not associative" won't impact vllm?
> 
>     5. You mentioned "fp16 matrix multiplication". If I change vllm parameter "--dtype" to be float32, will it fix this issue?  (I understand the GPU memory will be double).
>        Sorry for more questions, just be curious about the root cause details and possible workaround. :-)

@robertgshaw2-neuralmagic, could you please help to check my previous questions? Thanks in advance!

**Comment by tonyaw** [comment]
@robertgshaw2-neuralmagic , I dig it deeper, and still can't get why batching(max_num_seq>1) can lead to undeterministic result.
As I "enable-chunked-prefill", max_num_batched_tokens is set to 512 tokens.
It means vllm processes 512 tokens(either for prefill or decode) per step.

For the single step "_AsyncLLMEngine.step_async" -> "GPUExecutorAsync.execute_model_async", it is done in a single Python coroutine. It means all the processing in the vllm step is done in sequence(not parallel).

If my understanding is right, then when and where "fp16 matrix multiplication associative" happens as the single vllm step is done in sequence, and there can be only one step in same time.
