### ISSUE TITLE
[Bug]: Error: No available node types can fulfill resource request

### ISSUE THREAD

**Issue by thies1006** [vllm-project/vllm#7815]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

I'm testing a Llama3.1-70B on two nodes with 2x8 L4 GPUs. It works fine with v0.5.4.
```python -m vllm.entrypoints.openai.api_server --model /secondary/thies/Hermes-3-Llama-3.1-70B/ --tensor-parallel-size 16 --max-num-batched-tokens 8192 --gpu-memory-utilization 0.85 --distributed-executor-backend=ray```

Now when I upgrade to master I get this error:
```
(autoscaler +7s) Error: No available node types can fulfill resource request {'node:<IP>': 0.001, 'GPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
INFO 08-23 10:16:22 ray_utils.py:174] Waiting for creating a placement group of specs for 10 seconds. specs=[{'node:<IP>': 0.001, 'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}]. Check `ray status` to see if you have enough resources.
```

ray status says:

```======== Autoscaler status: 2024-08-23 10:22:31.765585 ========
Node status
---------------------------------------------------------------
Active:
 1 node_fd78035d54d28a1357f3b6d412a3a6d11595cdb60f962e3b6ba51777
 1 node_493f441c8cd5c582361ee8634f5cd1c2cb3413983a27ae9a083d1d55
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/128.0 CPU
 0.0/16.0 GPU
 0B/1.59TiB memory
 0B/372.53GiB object_store_memory

Demands:
 (no resource demands)```

**Comment by RickyCui010** [comment]
Then why doesn't the IP address that ray is looking for match the one used during the cluster startup? Where exactly is the issue?

**Comment by qingchen177** [comment]
How did you solve this problem？
I encountered the same problem, I have two IPs, one is the public network connection IP1, and the other is the IP container communication IP2. My ray start is
IP2， But the ray looking for is ip1

**Comment by thies1006** [comment]
I don't know how to change the IP which ray uses. I never tried, I just use the working one.
Did you check the routing of your network (outbound IP)?

**Comment by qingchen177** [comment]
Okay, the outbound IP addresses of my two containers are not compatible. Thank you for your reply！

**Comment by seungduk-yanolja** [comment]
https://github.com/vllm-project/vllm/blob/80c751e7f68ade3d4c6391a0f3fce9ce970ddad0/vllm/v1/executor/ray_utils.py#L250
This line is the issue. There could be a mismatch with the actual IP address used to setup ray.

**Comment by Neo9061** [comment]
I have the same issue when I try to run multi-node inference for DeepSeek V3 with two 8*H100.

After I setup the ray cluster, I am able to see following by `ray status`.

```
======== Autoscaler status: 2025-02-02 19:52:24.223188 ========
Node status
---------------------------------------------------------------
Active:
 1 node_e6107ebf05bbc00
 1 node_4c9baf725a0e654
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/384.0 CPU
 0.0/16.0 GPU
 0B/3.88TiB memory
 0B/19.46GiB object_store_memory

Demands:
 {'node:ec2-<MY ADDRESS>.us-west-2.compute.amazonaws.com': 0.001, 'GPU': 1.0} * 1, {'GPU': 1.0} * 15 (PACK): 1+ pending placement groups
```

I used the lastest docker of vllm and followed the latest instruction [here](https://github.com/vllm-project/vllm/blob/main/docs/source/serving/distributed_serving.md#troubleshooting-incorrect-hardware-driver) to include `-e VLLM_HOST_IP` but still, I have those type of  error 
```
(autoscaler +10m11s, ip=172.31.42.4) Error: No available node types can fulfill resource request {'node:ec2-<MY ADDRESS>.us-west-2.compute.amazonaws.com': 0.001, 'GPU': 1.0}. Add suitable node types to this cluster to resolve this issue.
INFO 02-02 19:36:47 ray_utils.py:212] Waiting for creating a placement group of specs for 630 seconds. specs=[{'node:<MY ADDRESS>.us-west-2.compute.amazonaws.com': 0.001, 'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}]. Check `ray status` to see if you have enough resources.
```

Is there any sanity checking i can do to see if those error comes from the issue mentioned in this thread?

**Comment by WangJianQ-0118** [comment]
> [vllm/vllm/v1/executor/ray_utils.py](https://github.com/vllm-project/vllm/blob/80c751e7f68ade3d4c6391a0f3fce9ce970ddad0/vllm/v1/executor/ray_utils.py#L250)
> 
> Line 250 in [80c751e](/vllm-project/vllm/commit/80c751e7f68ade3d4c6391a0f3fce9ce970ddad0)
> 
>  current_ip = get_ip() 
> 
> This line is the issue. There could be a mismatch with the actual IP address used to setup ray.
> We can use `VLLM_HOST_IP` to override the IP.
> ```
> VLLM_HOST_IP=xxx.xxx.xxx.xxx vllm serve deepseek-ai/DeepSeek-V3 ...
> ```


加了 VLLM_HOST_IP=xxx.xxx.xxx.xxx 之后
会出现一个新问题：
(pid=1058) INFO 02-09 02:31:08 __init__.py:190] Automatically detected platform cuda.
ERROR 02-09 02:31:11 engine.py:389] Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.
ERROR 02-09 02:31:11 engine.py:389] Traceback (most recent call last):
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 380, in run_mp_engine
ERROR 02-09 02:31:11 engine.py:389]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 02-09 02:31:11 engine.py:389]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 123, in from_engine_args
ERROR 02-09 02:31:11 engine.py:389]     return cls(ipc_path=ipc_path,
ERROR 02-09 02:31:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 75, in __init__
ERROR 02-09 02:31:11 engine.py:389]     self.engine = LLMEngine(*args, **kwargs)
ERROR 02-09 02:31:11 engine.py:389]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
ERROR 02-09 02:31:11 engine.py:389]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 02-09 02:31:11 engine.py:389]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 262, in __init__
ERROR 02-09 02:31:11 engine.py:389]     super().__init__(*args, **kwargs)
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 51, in __init__
ERROR 02-09 02:31:11 engine.py:389]     self._init_executor()
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 90, in _init_executor
ERROR 02-09 02:31:11 engine.py:389]     self._init_workers_ray(placement_group)
ERROR 02-09 02:31:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 227, in _init_workers_ray
ERROR 02-09 02:31:11 engine.py:389]     raise ValueError(
ERROR 02-09 02:31:11 engine.py:389] ValueError: Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 391, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 380, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 123, in from_engine_args
    return cls(ipc_path=ipc_path,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 75, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 262, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 51, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 90, in _init_executor
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 227, in _init_workers_ray
    raise ValueError(
ValueError: Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.
*** SIGTERM received at time=1739097071 on cpu 95 ***
PC: @     0x7fa5c96777f8  (unknown)  clock_nanosleep
    @     0x7fa5c95d4520  (unknown)  (unknown)
    @ ... and at least 3 more frames
[2025-02-09 02:31:11,663 E 15439 15439] logging.cc:460: *** SIGTERM received at time=1739097071 on cpu 95 ***
[2025-02-09 02:31:11,663 E 15439 15439] logging.cc:460: PC: @     0x7fa5c96777f8  (unknown)  clock_nanosleep
[2025-02-09 02:31:11,663 E 15439 15439] logging.cc:460:     @     0x7fa5c95d4520  (unknown)  (unknown)
[2025-02-09 02:31:11,663 E 15439 15439] logging.cc:460:     @ ... and at least 3 more frames
Exception ignored in atexit callback: <function shutdown at 0x7fa44c55bd80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 1910, in shutdown
    time.sleep(0.5)
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 1499, in sigterm_handler
    sys.exit(signum)
SystemExit: 15
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 204, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 44, in serve
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 875, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 136, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 230, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

**Comment by hahmad2008** [comment]
@youkaichao @Neo9061  I already set the env variable `VLLM_HOST_IP` and still have the same error, could you please check?

https://github.com/vllm-project/vllm/issues/13521

**Comment by hahmad2008** [comment]
@Neo9061 @youkaichao Any help please on this issue? https://github.com/vllm-project/vllm/issues/13521

**Comment by qingchen177** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vllm-project/vllm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月20日(星期四) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vllm-project/vllm] [Bug]: Error: No available node types can fulfill resource request (Issue #7815)



   
@Neo9061 @youkaichao Any help please on this issue? #13521

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  hahmad2008 left a comment (vllm-project/vllm#7815)
 
@Neo9061 @youkaichao Any help please on this issue? #13521

**Comment by yananchen1989** [comment]
also face this issue with vllm ver: 0.7.3

`vllm  serve google/gemma-2-27b-it           --api-key "yyy" --port 1703 --gpu_memory_utilization 0.95 --tensor-parallel-size 4  --dtype float16  --quantization bitsandbytes --load_format bitsandbytes --enforce_eager`

and add `VLLM_HOST_IP=10.225.68.29` does not help.


> INFO 02-26 11:01:06 __init__.py:207] Automatically detected platform cuda.
> INFO 02-26 11:01:06 api_server.py:912] vLLM API server version 0.7.3
> INFO 02-26 11:01:06 api_server.py:913] args: Namespace(subparser='serve', model_tag='google/gemma-2-27b-it', config='', host=None, port=1703, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key='yyy', lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='google/gemma-2-27b-it', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='bitsandbytes', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.95, num_gpu_blocks_override=None, 
> max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization='bitsandbytes', rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=True, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function ServeSubcommand.cmd at 0x7daf3a593100>)
> INFO 02-26 11:01:06 api_server.py:209] Started engine process with PID 17136
> WARNING 02-26 11:01:07 config.py:2448] Casting torch.bfloat16 to torch.float16.
> INFO 02-26 11:01:09 __init__.py:207] Automatically detected platform cuda.
> WARNING 02-26 11:01:09 config.py:2448] Casting torch.bfloat16 to torch.float16.
> INFO 02-26 11:01:11 config.py:549] This model supports multiple tasks: {'classify', 'score', 'reward', 'generate', 'embed'}. Defaulting to 'generate'.
> WARNING 02-26 11:01:11 config.py:628] bitsandbytes quantization is not fully optimized yet. The speed can be slower than 
> non-quantized models.
> INFO 02-26 11:01:11 config.py:1382] Defaulting to use ray for distributed inference
> WARNING 02-26 11:01:11 cuda.py:95] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
> WARNING 02-26 11:01:11 config.py:685] Async output processing is not supported on the current platform type cuda.        
> INFO 02-26 11:01:13 config.py:549] This model supports multiple tasks: {'classify', 'generate', 'reward', 'score', 'embed'}. Defaulting to 'generate'.
> WARNING 02-26 11:01:13 config.py:628] bitsandbytes quantization is not fully optimized yet. The speed can be slower than 
> non-quantized models.
> INFO 02-26 11:01:13 config.py:1382] Defaulting to use ray for distributed inference
> WARNING 02-26 11:01:13 cuda.py:95] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
> WARNING 02-26 11:01:13 config.py:685] Async output processing is not supported on the current platform type cuda.        
> INFO 02-26 11:01:14 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.3) with config: model='google/gemma-2-27b-it', 
> speculative_config=None, tokenizer='google/gemma-2-27b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.BITSANDBYTES, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, 
> collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=google/gemma-2-27b-it, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=True,     
> 2025-02-26 11:01:15,453 INFO worker.py:1636 -- Connecting to existing Ray cluster at address: 10.225.68.29:6379...
> 2025-02-26 11:01:15,463 INFO worker.py:1821 -- Connected to Ray cluster.
> WARNING 02-26 11:01:15 ray_utils.py:327] The number of required GPUs exceeds the total number of available GPUs in the placement group.
> INFO 02-26 11:01:25 ray_utils.py:221] Waiting for creating a placement group of specs for 10 seconds. specs=[{'node:10.225.68.29': 0.001, 'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}]. Check `ray status` to see if you have enough resources, and make sure the IP addresses used by ray cluster are the same as VLLM_HOST_IP environment variable specified in each node if you are running on a multi-node.
> INFO 02-26 11:01:45 ray_utils.py:221] Waiting for creating a placement group of specs for 30 seconds. specs=[{'node:10.225.68.29': 0.001, 'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}]. Check `ray status` to see if you have enough resources, and make sure the IP addresses used by ray cluster are the same as VLLM_HOST_IP environment variable specified in each node if you are running on a multi-node.
> INFO 02-26 11:02:25 ray_utils.py:221] Waiting for creating a placement group of specs for 70 seconds. specs=[{'node:10.225.68.29': 0.001, 'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}, {'GPU': 1.0}]. Check `ray status` to see if you have enough resources, and make sure the IP addresses used by ray cluster are the same as VLLM_HOST_IP environment variable specified in each node if you are running on a multi-node.

**Comment by ruisearch42** [comment]
Hi @yananchen1989 Can you share the output for `ray status`? What does the deployment topology look like? Does IP 10.225.68.29 correspond to a worker/container that owns GPU?

**Comment by yananchen1989** [comment]
@ruisearch42  hi more details here: https://github.com/vllm-project/vllm/issues/13909
including ray status.

what do you mean  deployment topology ?  I just pip install vllm.

the ip 29 is from
ifconfig:

> enp0s31f6: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         ether 10:98:19:2f:79:8e  txqueuelen 1000  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
>         device interrupt 19  memory 0x80a00000-80a20000
> 
> enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.225.68.29  netmask 255.255.255.128  broadcast 10.225.68.127
>         inet6 fe80::2f4e:43b0:3377:66d9  prefixlen 64  scopeid 0x20<link>
>         ether 10:98:19:2f:79:8f  txqueuelen 1000  (Ethernet)
>         RX packets 6229019  bytes 8667362215 (8.6 GB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 2433565  bytes 164832133 (164.8 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 1551819  bytes 154164417 (154.1 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1551819  bytes 154164417 (154.1 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

sorry i do not have too much knowledge about ray.
this is a new machine so i want to install vllm as the same way with my old machine.

**Comment by ruisearch42** [comment]
@yananchen1989 Yeah I was asking how the network was set up, what are the nodes, what are their IPs etc.
Let's bring the discussion to #13909

**Comment by StoKou** [comment]
Has there been a solution? I'm using a pre-built Ray startup script to connect the nodes. Using VLLM during Verl training works fine, but the same problem occurs when starting model inference using VLLM alone.
