### ISSUE TITLE
 Issue Building vllm Wheel: Unsupported GPU Architecture 'compute_89'

### ISSUE THREAD

**Issue by ryanshrott** [vllm-project/vllm#803]
I'm trying to build the vllm package from source (pip install vllm), but I'm encountering an error related to CUDA and GPU architecture. I am using RTX 4090. Here are the crucial parts of the log:

```
Building wheels for collected packages: vllm
Building wheel for vllm (pyproject.toml) ... error
error: subprocess-exited-with-error

...

building 'vllm.cache_ops' extension
Emitting ninja build file ...

...

/usr/local/cuda/bin/nvcc  -I/tmp/pip-build-env-... (other flags and paths)
nvcc fatal   : Unsupported gpu architecture 'compute_89'
```

Here is my compute cluster:
---
6790722
Age:15 min.[Remaining](https://vast.ai/faq#Instances):1d 19h71.69.80.64:44536-44750North Carolina, US1x RTX 409081.8  TFLOPS
m:9663host:39244verified0.3/24.6 GB
3506.9 GB/s
ROME2D16
PCIE 4.0, 8x12.5 GB/s
AMD EPYC 7662 64-Core Processor
25.6/256 cpu
4/52 GB
nvme
4972 MB/s6.9/21.0 GB
516.4 Mbps514.0 MbpsMax CUDA: 12.2
 
GPU: 0% 35C , CPU: 4% Status: success, running pytorch/pytorch_2.0.1-cuda11.7-cudnn8-devel/jupyter
$0.263/hr 
Current State : running Next State : running
Docker Image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

Image Runtype : jupyter_direc ssh_direc ssh_proxy

Environment :
{
  "JUPYTER_DIR": "/"
}

Docker Args:

Onstart: env | grep _ >> /etc/environment; echo 'starting up'

---

It seems that the nvcc compiler doesn't support the 'compute_89' GPU architecture. I'm using CUDA version 11.7 on a RTX 4090.

Has anyone encountered this issue before? Any suggestions on how to resolve it?

**Comment by fengenbao** [comment]
Upgrading your Cuda version to 11.8 can solve this problem

**Comment by WoosukKwon** [comment]
@ryanshrott As @fengenbao answered, compiling CUDA kernels for Lovelace GPUs (i.e., SM 89) requires CUDA 11.8 or later. ([link](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/)). You can either upgrade your CUDA version or build vLLM for SM80/86 architectures with CUDA 11.7, since [SM89 is compatible with SM80 and SM86](https://docs.nvidia.com/cuda/ada-compatibility-guide/index.html#applications-built-using-cuda-toolkit-11-0-through-11-7).

For the later option, please insert `compute_capabilities = {80}` below the following line:
https://github.com/vllm-project/vllm/blob/c393af6cd70373ab88b22dbbe59e14bb80ea343d/setup.py#L52
