### ISSUE TITLE
[Misc]:  Question about Serving with Server API

### ISSUE THREAD

**Issue by JoanFM** [vllm-project/vllm#8033]
### API Server

I have been digging around VLLM. and I have observed that the API server actually holds a client to an RPC server.

I guess this is needed because of the multi model potential nature. But if I were to serve a single model instance, would it be recommended to use directly an `AsyncLLMEngine` behind my FastAPI app or any web server?

Thanks for the clarification.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by JoanFM** [comment]
Hey thanks，

This is quite interesting, however have you considered also simply using a ThreadPool to asynchronize blocking CPU actions? At the end most of the time you would be calling libraries releasing the GIL right?

**Comment by robertgshaw2-neuralmagic** [comment]
The issue is not asyncio related.

The issue is that on H100 with small models, the GPU forward part of the inner loop is very fast (this is the only section that releases the GIL) and we have CPU contention between the rest of the inner_loop (`schedule` and `process_outputs`) operations and the FastAPI server. So running in a ThreadPool will not fix the issue because none of the operations that are causing CPU contention release the GIL

**Comment by JoanFM** [comment]
Thanks for the reply.

**Comment by robertgshaw2-neuralmagic** [comment]
> Thanks for the reply.

@JoanFM Are you running into some issues? The RPC caused some problems in v0.5.4 that we stabilized in v0.5.5, but if there are any ongoing problems I would greatly appreciate any reproduction instructions

**Comment by JoanFM** [comment]
Hey, no not issue thanks.
