### ISSUE TITLE
perf: investigate use of tensor cores (wmma, wgmma)?

### ISSUE THREAD

**Issue by jon-chuang** [vllm-project/vllm#899]
Seems that the implementation of dot product does not utilize tensor core. I wonder if there is possibility of using these?

https://github.com/vllm-project/vllm/blob/d2b2eed67c49cdda3c1d6fa09ee2ec128b318138/csrc/attention/dtype_float32.cuh#L122

There may be some overhead but I understand that one already tries to tile Q along the HEAD_DIM. It may be an argument to try to use a higher level compiler (like triton) to manage the thread indices and tiling.

Btw, why does this use uint16? I think this is the wrong file? Or simply because there is no C++ type for f16? 🤔 

https://github.com/vllm-project/vllm/blob/d2b2eed67c49cdda3c1d6fa09ee2ec128b318138/csrc/attention/dtype_float16.cuh#L1

**Comment by WoosukKwon** [comment]
Hi @jon-chuang, thanks for the question. In the generation phase, the attention op becomes a vector-matrix multiplication because there's a single query vector (corresponding to the input token) while there are multiple key/value vectors (corresponding to the context). Since the tensorcores are designed for matrix-matrix multiplications with certain shapes, it's not beneficial to use them for attention in the generation phase.

**Comment by WoosukKwon** [comment]
> Btw, why does this use uint16? I think this is the wrong file? Or simply because there is no C++ type for f16? 

Our paged attention kernel was adapted from NVIDIA FasterTransformer, which used the weird data type. I guess it's to work around some annoying issues when using the `half` data type, but not sure about the exact reasons for the choice. Because the kernel uses some assembly code for computing dot products, using `uint16_t` does not affect the functionality of the kernel.

**Comment by durant1999** [comment]
> Hi @jon-chuang, thanks for the question. In the generation phase, the attention op becomes a vector-matrix multiplication because there's a single query vector (corresponding to the input token) while there are multiple key/value vectors (corresponding to the context). Since the tensorcores are designed for matrix-matrix multiplications with certain shapes, it's not beneficial to use them for attention in the generation phase.

Great explanation! this helps me a lot...
